### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#202]
Sorry for the aggressive change recently. I'm just trying to get things in shape for tagging 1.0, with the intention for greater stability at that point.

------

Sometime before calling this "1.0" I am hoping to:

1. #438
2. #246  
3. #310
4. #168 
5. #150
6. ~remove the `affixation-function` in favor of a hopefully new `decoration-function` (a feature planned to supplant affixation, but it has yet to be written and submitted for inclusion in Emacs)~ (sadly, this won't happen anytime soon)

**Comment by jellelicht** [comment]
Is there an enhanced roadmap for 1.0, or are there any specific things that need polish and/or testing?

**Comment by bdarcus** [comment]
I should probably remove this, as the milestone feature is more efficient for tracking.

https://github.com/bdarcus/citar/milestone/3

I think the most important issue is actually the one I just tagged for 1.0: #438.
