### ISSUE TITLE
How should new "open" commands work?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#226]
The WIP refactor in #222 includes removing the bibtex-completion dependency for the "open" commands.

This gives us opportunities, but also can be a bit overwhelming.

So how should these work?

My current thinking is:

- `bibtex-actions-open` optionally prompts with grouped files, (maybe) links, notes options; a kind of dashboard for related resources
- `bibtex-actions-open-pdf` rename to `bibtex-actions-open-library-files`, but opens directly, but function is a configurable choice of `find-file` (that will open files in Emacs), `xdg-open` (that will open externally), etc
- `bibtex-actions-open-notes` uses `find-file` to open within Emacs

Other options:

- Consult has [`consult-find`](https://github.com/minad/consult/blob/271b89af7f59acaa54123d36abb9efdcea0ddc38/consult.el#L4323) and [`consult-file-externally`](https://github.com/minad/consult/blob/271b89af7f59acaa54123d36abb9efdcea0ddc38/consult.el#L3146) (supports wider platform range), though can just borrow some of this code.

See #191.

**Comment by bdarcus** [comment]
OK, @salutis @aikrahguzar - here's where #222 stands; I have:

1. changed `bibtex-actions-read` to use `completing-read` by default, with an optional `:multiple` arg
2. changed `bibtex-actions-open-pdf` to `bibtex-actions-open-library-files`, which uses `completing-read` (so you select one candidate; not multiple)
3. removed the `bibtex-completion` dependency on this, so handle it all internally
4. added a `bibtex-actions-open-library-file-external` defcustom on the file-open function, and when t, `bibtex-actions-open-files` uses `xdg-open` by default, for example, but works on other platforms.

I'm kind of stuck now, though, on the question of how this should work. Ideally I just want to merge #222 and then discuss the broader possibilities at a more leisurely pace.

All of this stuff is connected though; if we want the open commands to use multiple, then I need to change other code.

**Comment by bdarcus** [comment]
Actually, I think maybe all commands should just take a list of keys. Otherwise it just gets complicated.

**Comment by aikrahguzar** [comment]
>     1. changed `bibtex-actions-read` to use `completing-read` by default, with an optional `:multiple` arg

Why this? What we have now seems really good to me. If I want 1 entry I can use enter to select one. If I want more multiple, I use tab to add them to selected group. I don't see any need for a separate option.   
 
> I'm kind of stuck now, though, on the question of how this should work. Ideally I just want to merge #222 and then discuss the broader possibilities at a more leisurely pace.

I only use bibtex-actions to insert citations actually so for me everything works perfectly right now.

But for broader stuff, what are we missing now? It seems to me the only thing missing is parsing the filepaths for in entry related files. Bibtex-completions tries to deal with every possibility at one place and as a result code gets messy. I would say we should do something simple if anything but let the user supply a function to handle quirks like https://github.com/tmalsburg/helm-bibtex/issues/105
 
Though I guess the first question here is if `parsebib` does anything toward giving us filepaths instead of a raw string.

> All of this stuff is connected though; if we want the open commands to use multiple, then I need to change other code.

I would say `embark` should be the way to deal with opening multiple files.

**Comment by bdarcus** [comment]
> > ```
> > 1. changed `bibtex-actions-read` to use `completing-read` by default, with an optional `:multiple` arg
> > ```
> 
> Why this? What we have now seems really good to me. If I want 1 entry I can use enter to select one. If I want more multiple, I use tab to add them to selected group. I don't see any need for a separate option.

Two things:

1. the new open functions only take a single key, and I was worried about complexity changing to multiple.
2. things like #161, which is also related to 1

But I'm not sure ATM.

> > I'm kind of stuck now, though, on the question of how this should work. Ideally I just want to merge #222 and then discuss the broader possibilities at a more leisurely pace.
> 
> I only use bibtex-actions to insert citations actually so for me everything works perfectly right now.
> 
> But for broader stuff, what are we missing now? 

Main thing is to fix a bug or two introduced by the above, or remove it, and adapt the pre-existing code.

> It seems to me the only thing missing is parsing the filepaths for in entry related files. Bibtex-completions tries to deal with every possibility at one place and as a result code gets messy. I would say we should do something simple if anything but let the user supply a function to handle quirks like [tmalsburg/helm-bibtex#105](https://github.com/tmalsburg/helm-bibtex/issues/105)

Yeah, makes sense.

> Though I guess the first question here is if `parsebib` does anything toward giving us filepaths instead of a raw string.
> 
> > All of this stuff is connected though; if we want the open commands to use multiple, then I need to change other code.
> 
> I would say `embark` should be the way to deal with opening multiple files.

But how does this relate to your first point above?

BTW, the two main embark devs do plan to enhance it to allow multi-actions with completing-read.

**Comment by aikrahguzar** [comment]
> Two things:
>     1. the new open functions only take a single key, and I was worried about complexity changing to multiple.

I don't think it should be complex. We can just concat the list of files offered, maybe tagged with key so they can be grouped according to the origin. 

>     2. things like [open-entry should use completing-read #161](https://github.com/bdarcus/bibtex-actions/issues/161), which is also related to 1

This makes sense, but I still think `completing-read` should be used only for such cases. Since selecting one entry with crm doesn't take any extra keystroke compared to cr.

> Main thing is to fix a bug or two introduced by the above, or remove it, and adapt the pre-existing code.

I guess, it makes sense to invite people to test this branch so they can find bugs. It is already an improvement in some respects especially opening related files that are not pdfs so people wanting that should test it. 

Adapting existing code can be done slowly.  
 
> But how does this relate to your first point above?

I think generally crm seems to be for cases where it makes sense to wait till the selection is complete to perform the final action e.g. inserting citations. For opening files I only see a bunch of sequential actions that can be performed as soon as there is trigger so cr + embark seems like a better choice.  

Though I don't see an implementation for `bibtex-actions-read` yet so maybe I am not seeing what you have in mind.

**Comment by bdarcus** [comment]
> > Two things:
> > 1. the new open functions only take a single key, and I was worried about complexity changing to multiple.
> 
> I don't think it should be complex. We can just concat the list of files offered, maybe tagged with key so they can be grouped according to the origin.

Where; in `files-for-keys`?

Maybe when you have time, you can propose that change?
  
> > But how does this relate to your first point above?
> 
> I think generally crm seems to be for cases where it makes sense to wait till the selection is complete to perform the final action e.g. inserting citations. For opening files I only see a bunch of sequential actions that can be performed as soon as there is trigger so cr + embark seems like a better choice.

Yes, consistent with what I was thinking.

> Though I don't see an implementation for `bibtex-actions-read` yet so maybe I am not seeing what you have in mind.

What I had in the code, since reverted, was just:

```elisp
(bibtex-actions-read :multiple t)
```

That was easy enough, but it does introduce issues elsewhere.

**Comment by bdarcus** [comment]
Except, there still seems a contradiction between your first point and the subsequent one on embark ;-)

To me, the only command that must be multiple is as you said: inserting citations.

**Comment by aikrahguzar** [comment]
> Except, there still seems a contradiction between your first point and the subsequent one on embark ;-)
> 
> To me, the only command that must be multiple is as you said: inserting citations.

I concede that and inserting citations is the only command I use so it looms very large for me. What I was trying to say is that if you want to maintain of the two `bibtex-actions-read`, crm does it without sacrificing much. But having both makes sense if it isn't much more code.

 I don't think `bibtex-actions-open` will share much code with `bibtex-actions-read` and for it going with just cr makes sense since it seems somewhat simpler. BTW I made a typo earlier, I meant to say that I hadn't seen an implementation of `bibtex-actions-open`.

**Comment by aikrahguzar** [comment]
> Where; in `files-for-keys`?

No, I was thinking when we are offering candidates for `bibtex-actions-open`. But it can be done pretty easily, without the metdata it is just`(seq-mapcat #'files-for-key keys)`

**Comment by bdarcus** [comment]
> > Where; in `files-for-keys`?
> 
> No, I was thinking when we are offering candidates for `bibtex-actions-open`. But it can be done pretty easily, without the metdata it is just`(seq-mapcat #'files-for-key keys)`

But then that would be duplicated for the different open commands?

Or are you advocating dropping some of them?

**Comment by bdarcus** [comment]
Also, the title of the issue was a question: how should this all work?

The code reflects a first stab, upon which to iterate. Since this piece is
all internal now, we have quite a bit of flexibility.

**Comment by salutis** [comment]
@bdarcus 

> You're going to need to be more specific, particularly on the "fails to do so". What does that mean?

For instance, `-open-link` says "No link found for ..." That is correct, as there is no link. But then, why would it offer to open a link if there is none? In other words, the list should include only the BibTeX entries that actually have some link to open.

**Comment by salutis** [comment]
@bdarcus 

> Also, the title of the issue was a question: how should this all work? The code reflects a first stab, upon which to iterate. Since this piece is all internal now, we have quite a bit of flexibility.

Yup, that is why I dumped all my "WTF moments" into the issue.

P.S. `-open` could perhaps also include the BibTeX entry itself. I would expect it to show everything that could be opened: links, notes, files, and the entry itself.

**Comment by bdarcus** [comment]
> @bdarcus
> 
> > You're going to need to be more specific, particularly on the "fails to do so". What does that mean?
> 
> For instance, `-open-link` says "No link found for ..." That is correct, as there is no link. But then, why would it offer to open a link if there is none? In other words, the list should include only the BibTeX entries that actually have some link to open.

Gotcha.

We may have talked about this before, but while we can do that, the downside is it's not reversible.

The affixation function in Emacs 28 does should you which items have links, but that's not helpful if you're using an earlier version.

I may address that with a different approach that will work in Emacs 27.

**Comment by bdarcus** [comment]
> P.S. `-open` could perhaps also include the BibTeX entry itself

I thought about that, but there are wrinkles.

Opening multiple files or links makes sense, but not multiple BibTeX entries.

How would you deal with that?

**Comment by salutis** [comment]
@bdarcus 

> The affixation function in Emacs 28 shows you which items have links etc, but that's not helpful if you're using an earlier version.

In my opinion, if `RET` results in an error ("No link found for ..."), the item should be either (1) disabled for selection with `RET` or (2) hidden from the list altogether. As it stands, `RET` does nothing but resets the context for the user, which does nothing but annoys them, no?

> Opening multiple files or links makes sense, but not multiple BibTeX entries.
>
> How would you deal with that?

This is a false proposition. For instance, I have never opened multiple files or links, but I regularly need to open multiple BibTeX entries to improve their publisher, links, or title field. Further, I think all "open" APIs should behave in exactly the same way.

**Comment by bdarcus** [comment]
> This is a false proposition. For instance, I have never opened multiple files or links, but I regularly need to open multiple BibTeX entries to improve their publisher, links, or title field. 

But you're missing something fundamental in my question: how do you open multiple entries in the same file?

Bibtex-completion et al doesn't: it only opens the first one, for example..

> Further, I think all "open" APIs should behave in exactly the same way.

Per above, that requires choices and trade-offs.

I could remove ability to select multiple keys on the open commands, but have a feeling many people would think that less than ideal, probably me included.

**Comment by bdarcus** [comment]
> In my opinion, if `RET` results in an error ("No link found for ..."), the item should be either (1) disabled for selection with `RET` or (2) hidden from the list altogether.

If the UI shows you if something is present, why would you hit RET on a candidate that shows nothing?

If I remove those items from the list, the downside is you can't get them back, without exiting and opening a different command. In some (many?) cases, I would argue, that will be more annoying.

I did earlier use the "initial input" approach to pre-filtering, which could be reversed easily, but it was an abuse of that feature, and didn't work well with `consult---read-multiple`.

**Comment by salutis** [comment]
> But you're missing something fundamental in my question: how do you open multiple entries in the same file?

Oh, I forgot that not everyone stores one BibTeX entry per file, like I do. Still, Emacs does not couple files and windows together, like modern editors do, so we can open multiple windows at the correct positions, right? 

> I could remove ability to select multiple keys on the open commands, but have a feeling many people would think that less than ideal, probably me included.

Personally, I would prefer single-item selection by default and multi-item selection on `C-u` or something along those lines. I can live with pressing `RET` twice everywhere, but it gets old.

**Comment by bdarcus** [comment]
> This confuses me. Why would I want to get them back?

Explained best here:

https://github.com/bdarcus/bibtex-actions/issues/144#issuecomment-862139158

You may open a command to browse with one idea in mind, and then want access to other targets, and then to run a different action on them via `embark-act`.
