### ISSUE TITLE
Redo bibtex-actions-open with a grouped list of related resources

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#229]
Related to #226, this is a proposal to redo `bibtex-actions-open` to present a UI like this after selecting the keys, where it shows related documents, both local files and external URLs

![image](https://user-images.githubusercontent.com/1134/129789881-fd1b66b1-0933-409b-b9b9-ed905d5c81b1.png)

I think this is a good idea; just a question of how best to do it technically. Here's the first step:

![image](https://user-images.githubusercontent.com/1134/129796737-bfe0a58e-7e04-423d-b6f9-4c277c8c114e.png)

```elisp
(defun bibtex-actions-open (keys)
  (interactive (list (bibtex-actions-read :rebuild-cache current-prefix-arg)))
  (let* ((files
         (bibtex-actions-file--files-for-multiple-keys
          keys
          (append bibtex-actions-library-paths bibtex-actions-notes-paths)
          bibtex-actions-file-extensions))
        (chosen-files (completing-read-multiple "Files: " files)))
        (cl-loop for file in chosen-files do
                 (funcall bibtex-actions-file-open-function file))))
```

**Comment by bdarcus** [comment]
@minad - I have the basics of this working with grouped files:

![image](https://user-images.githubusercontent.com/1134/129800661-774c767e-e62c-4b7a-b4ec-682a58b6e09f.png)

How do I add links to the candidates list, with a different category?

I guess this is consult multi-source territory, but if it's easy, I'd prefer to avoid the dependency.

**Comment by bdarcus** [comment]
This is partially addressed in #222.

**Comment by bdarcus** [comment]
Seems easier to just use `consult--multi`, as `consult-dir` does:

![image](https://user-images.githubusercontent.com/1134/130327548-a230d8e0-2c6d-4103-a2e4-781948796c31.png)

**Comment by bdarcus** [comment]
.. or even just customize `consult-buffer`?

In any case, what I want is conceptually similar, but for the sources to also include related files and links.

**Comment by bdarcus** [comment]
I know you may not use this @aikrahguzar, but since you've worked on the related functionality, you may have some thoughts.

Here's a demo of what's possible with `consult--multi`; in this case mixing three sources specific to bibtex-actions, and one that consult.

![image](https://user-images.githubusercontent.com/1134/130358190-d13f4c09-c8c2-47a1-97c8-52de4fd5d24f.png)

Because they are each different categories, embark can attach different actions to them.

The questions I'm thinking about:

1. whether to really treat local files and "links" differently, or just bundle them in one list? So in that scenario, "links" and "files" would just be combined into something like "source documents".
2. require consult and just go with this? If I do go with this, I'll write at least one annotation function to make "notes" and "links"  look better.

**Comment by aikrahguzar** [comment]
>     2. require consult and just go with this? If I do go with this, I'll write at least one annotation function to make "notes" and "links"  look better. The disadvantage is an additional dependency, somewhere (could be a different package, for example), but the advantage is a lot of flexibility. For example, the "notes" section could easily swap in a different function that queries an `org-roam` database for notes that cite the reference in question, or could add a source for local documents that cite it.
> 

This seems nice. The only I can think of to add is that one advantage of consult would be the possibility of previews for files. Though doom disabled them for commands like `find-file` because they are too slow so it might not matter that much.

**Comment by bdarcus** [comment]
Really to these, consult also has "narrowing" support, which is active on Doom by default. If you haven't already, run `consult-buffer` and then `<`.

**Comment by bdarcus** [comment]
After thinking about this a bit, the plan:

- add code that will use `consult--multi` when present
- default sources/categories for "open" include:
    - files (file)
    - notes (file)
    - links (url)
- add a simple annotation for url (though I put in a request for this at marginalia)

Note that with those categories, embark and consult provide relevant actions for the candidates, as well as annotations.

**Comment by bdarcus** [comment]
See https://github.com/bdarcus/bibtex-actions/pull/295#issuecomment-922924035.

The problem (currently) with `consult--multi` is it uses `completing-read`, so would be inefficient to open multiple resources.

To quote myself:

> Maybe better to remove the prompt on `bibtex-actions-open`, or remove the command entirely, and then have a (possibly optional) prompt on the other open commands, but give them the appropriate completion category so that marginalia, consult and embark can provide extra functionality there?
