### ISSUE TITLE
Add biblio lookup?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#262]
I'm not sure this is a good idea, but while I'm thinking about it ...

Here's how the `biblio-lookup` interactive function works:

```elisp
(biblio-lookup 'biblio-crossref-backend "public space")
```
In `helm-bibtex`, you can pipe a search string to that, with the "fallback" section below disclosing as you type in the prompt:

![image](https://user-images.githubusercontent.com/1134/131195366-c6181185-433b-42e8-a14b-4feb7e508385.png)

With `ivy-bibtex`, "fallback" is just an action, that opens an action submenu,

How might this work in `completing-read` though?

**Comment by aikrahguzar** [comment]
This does seem difficult since we need both the search string and a selected entry.

But to me at least a better way would be to put these fallback options under an embark menu. I haven't looked at how embark targets work but can we use the search string as an emabrk target? The readme for embark says that `In the minibuffer, the target is the current top completion candidate`, so I assume the search string is not a default target and a custom one will be needed.

**Comment by bdarcus** [comment]
> But to me at least a better way would be to put these fallback options under an embark menu. I haven't looked at how embark targets work but can we use the search string as an emabrk target? The readme for embark says that `In the minibuffer, the target is the current top completion candidate`, so I assume the search string is not a default target and a custom one will be needed.

Worth considering, but I'm not sure how this would work, either from a technical POV, or UX.

**Comment by minad** [comment]
> I haven't looked at how embark targets work but can we use the search string as an emabrk target? 

There is `embark-become`. Is this what you are looking for?

**Comment by bdarcus** [comment]
> There is `embark-become`. Is this what you are looking for?

Unless there's something misconfigured here or in doom, I don't think so.

This is what I get when I invoke it:

```console
which-key: No bindings found in Act on embark-become 'state public space'
```

Is that expected?

Basically, what we're discussing here is a workflow by which you enter filter terms for the library, but if not finding anything, or what you're looking for, instead you run a search of online databases.

**Comment by minad** [comment]
`embark-become` is not a fallback, but it allows you to reuse the input string and inject it in another command. See https://github.com/oantolin/embark#switching-to-a-different-command-without-losing-what-youve-typed. I think this is approximately what you are looking for here modulo bugs? But maybe I misunderstood something. Of course one could also add a fallback action/menu item which then starts a biblio command, but I would find that pretty ugly and not in the spirit of Embark.

**Comment by bdarcus** [comment]
Let me see if I understand, using the example in the README.

If I go to change buffer and type "test" in the mini buffer prompt, then do `embark-act` and `embark-become`, I should then get an `M-x` prompt, where I can then do `find-file`?

**Comment by bdarcus** [comment]
Per my note on the PR, I'm thinking not to implement this, and have instead put an example on the wiki.

https://github.com/bdarcus/citar/wiki/Embark
