### ISSUE TITLE
bibtex-actions-insert-citation vs org-cite-insert

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#278]
Not sure how to handle this, but when using oc-bibtex-actions with org, one should not use `bibtex-actions-insert-citation` (or even `bibtex-actions-insert-key`), and instead use the native `org-cite-insert`.

Ideas I can think of:

1. don't autoload those commands at all
2. only autoload them subject to some condition; maybe a variable
3. don't touch autoload at all, but add a message when using the commands in org

**Comment by liebkne** [comment]
I have a large bibtex file (1500 entries)

`org-cite-insert` is super slow at the first time call (34s) while `bibtex-actions-insert-citation` is much faster (3s). I'd like to use `bibtex-actions-insert-citation` even with `oc`.

**Comment by bdarcus** [comment]
It's slow because you're using oc-basic for the insert processor; not bibtex-actions.

**Comment by liebkne** [comment]
Yes, that's why I said I still prefer to use `bibtex-actions-*` commands in this situation. It would be nice if this awesome package can deal with the new style `oc` link syntax.

**Comment by bdarcus** [comment]
> Yes, that's why I said I still prefer to use `bibtex-actions-*` commands in this situation. It would be nice if this awesome package can deal with the new style `oc` link syntax.

It can ;-)

https://github.com/bdarcus/bibtex-actions#configuration

Note: I may need to fix the example to include explicitly doing `setq org-cite-insert-processor 'oc-bibtex-actions`.

**Comment by liebkne** [comment]
Thanks, that works.

It would be helpful to include that in README. And I've thought `(setq org-cite-insert-processor 'oc-bibtex-actions)` will make `bibtex-action-insert-citations` to work with `oc` directly and now I understand I should use `org-cite-insert` even it's set :)

**Comment by bdarcus** [comment]
> It would be helpful to include that in README. 

Well, the link I posted was to the README. What more should I add; something in the first lines?

> And I've thought `(setq org-cite-insert-processor 'oc-bibtex-actions)` will make `bibtex-action-insert-citations` to work with `oc` directly and now I understand I should use `org-cite-insert` even it's set :)

Yes, we basically plugin to the org-cite infrastructure, and let it take over.

That's what this issue is about, because it confuses users. Basically, when using org-cite, there's no reason for the insert commands.

**Comment by liebkne** [comment]
I mean the `(setq org-cite-insert-processor 'oc-bibtex-actions)` part would be helpful for newbies :)
