### ISSUE TITLE
rewrite bibtex-actions-insert-citation

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#308]
We need feedback on this, particularly from latex and pandoc citation users.

As part of #246, @aikrahguzar is working on #307 to redo the insert commands to remove the bibtex-completion dependency.

This also means room to change how they work.

Should this work exactly the same? Differently in some way?

Possibilities I can see:

1. in latex-mode, for the UI to present the list of commands depending on which citation system one is using (natbib, biblatex, etc.)
2. for the UI in general to work more like in org-cite, where it adapts depending on the location of point

I also don't think these commands should be loaded if one is exclusively using org-cite (see #278). Not sure how best to address this though. Maybe just don't autoload, and require users to explicitly configure the loading?

**Comment by aikrahguzar** [comment]
>     2. for the UI in general to work more like in org-cite, where it adapts depending on the location of point

There is a limited form of point awareness in both bibtex-completion and the current implementation in the draft. If the point is inside a cite command, the keys are inserted and there isn't any prompt for choosing a citation command. Otherwise we prompt for one. But if we can be more context aware it would be better.

**Comment by rka97** [comment]
I think it's important to be able to configure citation text (kinda like how it's done in org-cite-insert). For example I want to be able to insert something like \citep[Chapter 1]{Smith20}, ideally there would be an embark action that allows this in 1 step (rather than the 2-step workflow of inserting a \citep, moving the point and then calling the citation command a la org-cite).

**Comment by bdarcus** [comment]
> ideally there would be an embark action that allows this in 1 step ...

Can you say more about this? How would that work?

**Comment by rka97** [comment]
I imagine it like this:
1. I call bibtex-actions-insert-citation and navigate to the right reference.
2. I press embark-act and choose one of the following:
    a. "Insert citation with pre-citation text"
    b. "Insert citation with post-citation text"
    c. "Insert citation with pre- and post- citation text"
3. On choosing it, I am prompted for the text, then it is inserted as \cite[text]{key}.

I think the default citation method is already configurable (i.e. to use \cite or \citep and so on). Another alternative to prompting the user for the text before inserting is to insert a snippet (like YASnippet), with placeholders for the pre- and/or post- text. But I think it's better to keep the package requirements/dependencies low. Does this explain what I mean?

**Comment by bdarcus** [comment]
Yes.

That reminds me:

Do we need to consider different logic for bibtex/natbib and biblatex/pandoc, given the the latter allows affixes (pre/post) per reference, and the former does not?

**Comment by aikrahguzar** [comment]
> I imagine it like this:
> 
>     1. I call bibtex-actions-insert-citation and navigate to the right reference.
> 
>     2. I press embark-act and choose one of the following:
>        a. "Insert citation with pre-citation text"
>        b. "Insert citation with post-citation text"
>        c. "Insert citation with pre- and post- citation text"
> 
>     3. On choosing it, I am prompted for the text, then it is inserted as \cite[text]{key}.

Except for embark which as @bdarcus said is an implementation detail, this doesn't seem too different from how it is currently. You choose the citations, then are presented with a list of citations commands, you choose one and are then prompted for optional arguments. In the current implementation in #307 this aspect remains the same, except that prompting for optional arguments is handed off `TeX-parse-macro` which makes it more flexible and customizable and it doesn't prompt for the remaining optional arguments if the first one is empty. 

The candidates list should be augmented with a suffix like `\cite[prenote][postote]{key1,key2}` to indicate which arguments will be prompted for. But you also want the duplicated options for the same command with and without prompting for optional args which I feel clutters the list and makes you scroll more while dismissing the prompt for optional args is just a `RET` which seems better to me. But that aspect can be made configurable. 

Is there anything else I am missing?

**Comment by bdarcus** [comment]
> The candidates list should be augmented with a suffix like `\cite[prenote][postote]{key1,key2}` to indicate which arguments will be prompted for. But you also want the duplicated options for the same command with and without prompting for optional args which I feel clutters the list and makes you scroll more while dismissing the prompt for optional args is just a `RET` which seems better to me. But that aspect can be made configurable.

I'm not totally following (maybe at some point screenshots would help?). By "suffix" do you mean an annotation or affixation?

And does this support my question above about different logic for natbib/bibtex vs biblatex?

**Comment by aikrahguzar** [comment]
> I'm not totally following (maybe at some point screenshots would help?). By "suffix" do you mean an annotation or affixation?

An annotation (I think, I am not really sure about the distinction) . 
 
> And does this support my question above about different logic for natbib/bibtex vs biblatex?

I don't have any idea about that. I have only ever used `bibtex`. Generally I would like context awareness to reduce the number of options presented but I have no idea how to do that or if it is possible.

**Comment by bdarcus** [comment]
An annotation is a suffix, affixation has prefix and suffix. So yes, annotation, as I use in the org-cite style editor.

> I would like context awareness to reduce the number of options presented but I have no idea how to do that or if it is possible.

Can you determine whether biblatex is active on a document?

I was also meaning if you do an annotation like that, it would be different for biblatex.

**Comment by bdarcus** [comment]
Forgot to link from the merged PR/commit: #357.
