### ISSUE TITLE
deprecate and remove insert-reference and add-pdf-to-library

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#310]
I've included I'm almost definitely removing the pdf commands (already marked obsolete and will be removed soon); not sure about the other two.

Now's the time for objections, and/or PRs, if you disagree.

----------

Another issue to pull out of #307. Feedback?

> What is left now is `insert-entry`, `insert-reference`, `add-PDF-attachment` and `add-pdf-to-library`. For all of these I am unsure how to go about them.

_Originally posted by @aikrahguzar in https://github.com/bdarcus/bibtex-actions/issues/307#issuecomment-928041463_

My thought is maybe we remove the last two, and for the second -> #245.

Not sure about the first.

But all of this needs user feedback, since I have no idea whether and how people are using these commands.

**Comment by localauthor** [comment]
I've pieced together the following rewrite of citar-insert-reference using citeproc.

Caveat: I do not understand more than the smallest fraction of citeproc-el, if that, and I'm learning elisp as I go, so, grains of salt.

Thoughts?

```
(defun citar-insert-reference (keys-entries)
  (interactive (list (citar-select-refs
                      :rebuild-cache current-prefix-arg)))
  (let* ((citelist (mapcar (lambda (x) (cons (cons 'id (cdr (assoc "=key=" x))) nil)) keys-entries))
         (proc (citeproc-create "~/.csl/chicago-fullnote-bibliography.csl"
			        (citeproc-itemgetter-from-bibtex citar-bibliography)
			        (citeproc-locale-getter-from-dir org-cite-csl-locales-dir)
			        "en-US"))
         (cites (list (citeproc-citation-create :cites citelist
					        :mode 'nil
					        :capitalize-first nil
					        :suppress-affixes nil)))
         (rendered-citations (progn 
                               (citeproc-append-citations cites proc)
                               (citeproc-render-bib proc 'plain))))
    (insert (car rendered-citations))))
```

**Comment by bdarcus** [comment]
Oh, cool.

I think this is probably the way to go, but there's one thing I'm a little leery of:

Citeproc is a pretty big library, and it doesn't seems wise to have it a hard dependency.

Will need to think on how to do this.

In any case, thanks!

**Comment by bdarcus** [comment]
Notes on `citar-insert-bibtex`:

I think we want to enhance `citar-open-entry` so it can open multiple entries `with-temp-buffer`, and then to use that in a list, and then `bibtex-kill-entry` and `bibtex-yank` to collect the content to then insert.

**Comment by bdarcus** [comment]
> Citeproc is a pretty big library, and it doesn't seems wise to have it a hard dependency.

I have another idea:

Use the same kind of template as for notes.

**Comment by bdarcus** [comment]
I've revised the title of this to reflect current status.

Really the primary remaining question is WTD with `citar-add-pdf-to-library`.

I've never used this command, but my impulse is just remove it and someone can always add a PR later to add back the functionality.
