### ISSUE TITLE
Bibtex-actions breaks org-cite-insert

### ISSUE THREAD

**Issue by JonathanReeve** [bdarcus/citar#332]
**Describe the bug**

I'm trying out the bibtex-actions and org-cite configuration from [this Doom PR](https://github.com/hlissner/doom-emacs/pull/5290), using [a fairly vanilla configuration, as far as I know](https://github.com/JonathanReeve/dotfiles/blob/org-cite-4/dotfiles/emacs/doom.d/config.el#L41) but it seems to have broken org-cite-insert. `bibtex-actions-insert-citation` also doesn't appear to work. When you run `org-cite-insert`, and select a bibliographic entry, you only get `[cite:@]`, i.e., no bibliographic key. When you run `bibtex-actions-insert-citation`, you get `ebib:nil`. 

I'm not sure if I'm configuring something wrong, but I've been trying to stay as close as possible to the configuration from that PR. 

**To Reproduce**
1. Open an .org file. 
2. Run `M-x org-cite-insert` or `SPC m @` in Doom. 
3. Select a bibliographic entry
4. Notice that the inserted entry is not the one you selected, but `[cite:@]`. 

**Expected behavior**

I expected the commands to insert a bibliographic key.

**Comment by bdarcus** [comment]
I'm going to assume this is resolved too; if not, feel free to reopen.
