### ISSUE TITLE
Bibtex-actions-open tries to open org files in a web browser

### ISSUE THREAD

**Issue by JonathanReeve** [bdarcus/citar#333]
**Describe the bug**

When using bibtex-actions-open to open related files, it correctly identifies my note files for given bibliographic entries, but it tries to `browse-url` a space-concatenated list of them. So when I try to open one of them, e.g. lukacs2005.org, instead of opening the org file in emacs, it opens a web browser to the address `/home/jon/Dokumentujo/Org/Roam/lukacs2005.org https://books.google.com/books?id=tccIZ1iOykEC`, i.e., the    

**To Reproduce**
1. Click on an org-cite entry or otherwise engage embark-act for it 
2. Choose `o`, `open source (file or link)`
3. In the vertico completion interface that pops up and says "Related resources:" there should be files and URLs listed. Choose either one 
4. Notice that no matter what you choose, a web page opens (for me, it opens in my web browser) to an address which is a space-concatenated list of all the files and URLs listed in the completion interface above

**Expected behavior**
I expected the org file I chose to be opened by emacs, and the URL to be opened by the web browser

**Comment by bdarcus** [comment]
Any update @JonathanReeve?

**Comment by JonathanReeve** [comment]
So I re-downloaded the files from [your org-cite PR](https://github.com/hlissner/doom-emacs/pull/5290), did a long and painful cleanup of my config, and removed lots of packages. Now everything works as expected. :shrug: So I suppose I should close this for now. But I'll chime in again at some point if I can figure out what package was conflicting with this one.
