### ISSUE TITLE
docs: defer loading oc-bibtex-actions in config?

### ISSUE THREAD

**Issue by tshu-w** [bdarcus/citar#340]
It take at least 0.5s+ (I have already require org first) to require oc-bibtex-actions on my side, which make opening the first org mode file is slow.
```emacs-lisp
(require 'org)
(benchmark-run (require 'oc-bibtex-actions))
```

**Comment by bdarcus** [comment]
See #342, which suggest this doesn't quite work.

**Comment by tshu-w** [comment]
after https://github.com/bdarcus/citar/pull/353, we don't need register-process if we want to defer citar-org
```emacs-lisp
(use-package citar-org
  :after oc
  :defer t
  :init
  (setq org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar))
```
