### ISSUE TITLE
Please expand comparison section

### ISSUE THREAD

**Issue by minad** [bdarcus/citar#359]
I know we've talked about this a few times, but I guess it would be generally useful to have an overview over the different packages, since there are so many. Some are libaries, some are frontends, some overlap or are orthogonal, some of them compete. It doesn't have to be in the README, it could also be in a wiki article linked from the README.

I know at least across the following packages. And just recently I stumbled over ebib by the same author as parsebib.

EDIT: The more I am looking the more I find. Maybe one needs a mind map like in Karthik's https://karthinks.com/software/latex-input-for-impatient-scholars/. Some libraries are quite large by first inspection, like citeproc, so it would be nice to know the scope of each of those packages.

## Frontends

* citar (frontend, latex/markdown/org, uses org-cite for org, based on parsebib and bibtex-completion. in flux, bibtex-completion might be removed, citeproc/biblio added?)
* ivy-bibtex, helm-bibtex, consult-bibtex (frontends to bibtex-completion, latex/markdown/org and more, does not use org-cite)
* bibtex-completion (middleware, based on parsebib and biblio)
* org-ref (frontend, only org, does not use org-cite, based on bibtex-completion/parsebib/citeproc)
* org-ref-cite (org-ref rebased on org-cite, dead?)
* org-roam-bibtex (org-roam/org-ref integration)
* ebib (bibtex/biblatex editor without having to edit the raw .bib files)

## Parsing/formatting of bibliographic databases

* citeproc (parser/formatter for csl and also partial parser for bibtex/biblatex? large library, overlap with parsebib. Dependency of org-cite oc-csl.el)
* citeproc-org (citeproc integration for org, replaced by org-cite oc.el?)
* parsebib (parser for bibtex, biblatex, csl-json, small library, overlap with citeproc?)
* org-cite oc.el (seems to replace citeproc-org)

## Retrieval of bibtex entries

* biblio, biblio-core, biblio-bibsonomy (retrieval of bibtex entries from various web sources)
* bibretrieve, bibslurp, gscholar-bibtex, empos/pyopl (retrieval of bibtex entries from various web sources)

## Others

* ~bibliothek~ (pdf manager only)

**Comment by bdarcus** [comment]
A number of those I've never even heard of!

**Comment by carlosperezm** [comment]
Now that we are talking about all the options, I have a question: can we say that `citar` also provides a replacement for `org-roam-bibtex` using only `org-cite`?
I haven't tried `citar`'s notes functionality yet  (I am still using `org-roam-bibtex` and ignoring `org-ref`), but that's my understanding of  what `citar-file-note-org-include` does from the README.

**Comment by bdarcus** [comment]
> ... can we say that citar also provides a replacement for org-roam-bibtex using only org-cite?

Yes, with the caveat it doesn't use org-capture, and it target OR V2.

**Comment by bdarcus** [comment]
For now I started a wiki page with your content, @minad, but edited by me to clarify a few questions, etc.

https://github.com/bdarcus/citar/wiki/Comparisons

Is there no way to allow open edits on the wiki, without having that apply to the code repo?
