### ISSUE TITLE
Installation examples in README.md do not seem to work

### ISSUE THREAD

**Issue by miikargh** [bdarcus/citar#364]
**Describe the bug**
I'm trying to install citar for org-mode according to the examples in README.md but I get the following error:
`Error (use-package): Failed to install citar-org: Package "citar-org-"
`

**To Reproduce**
Here's my init.el:
```
  (defvar miika/bibs '("~/bib/references.bib"))

  (use-package citar
    :custom
    (citar-bibliography miika/bibs))

  (use-package citar-org
    :no-require
    :custom
    (org-cite-global-bibliography my/bibs)
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar))
```

**Expected behavior**
Installing the packages without errors.

**Emacs version:**
GNU Emacs 28.0.60

**Additional context**
I've not found citar-org from list-packages.

Any help appreciated!

**Comment by bdarcus** [comment]
cc @roshanshariff 

It's included in the main citar package, so that's not the issue.

Really you just need to set those variables; the adapter itself should load when needed.

Can you try what happens without the `use-package` there, and just use `setq` for the processors?

**Comment by miikargh** [comment]
This seems to work, thanks!

```
  (defvar miika/bibs '("~/bib/references.bib"))

  (use-package citar
    :after org
    ;; :commands org-cite-insert
    :custom (citar-bibliography miika/bibs)
    :config
    (miika/leader-keys
      :keymap 'org-mode-map
      "ci" '(org-cite-insert :which-key "Insert citation"))
    (setq org-cite-global-bibliography miika/bibs)
    (setq org-cite-insert-processor 'citar)
    (setq org-cite-follow-processor 'citar)
    (setq org-cite-activate-processor 'citar))
```
