### ISSUE TITLE
Getting citar-markdown to work

### ISSUE THREAD

**Issue by andrasbarany** [bdarcus/citar#367]
### Issue

I'm trying to set up citations using citar in markdown but I cannot get them to work.

Using the information about `citar-org` in the README I tried the following.

```
(defvar legenda '("~/LaTeX/legenda.bib"))

(use-package citar-markdown
    :custom
    (citar-markdown-local-bib-files legenda)
    (citar-markdown-insert-keys 'citar))
```

I get the `citar-org` to work but when I try to insert a citation in a markdown file I don't see the `citar` minibuffer and I get the following error:

`Symbol’s function definition is void: citar-markdown-local-bib-files`

Am I doing something wrong? Did I miss some documentation?

**Comment by bdarcus** [comment]
It should "just work".

What happens if you remove that entire use-package statement?

**Comment by andrasbarany** [comment]
Nothing changes if I remove the use-package statement, still get the error about the function definition. I included it because if I do not have the analogous `citar-org` statement from the README, I don't get citations in `org` files either (I do get the minibuffer, but no cite-key is inserted).

Also no difference whether I use `pandoc-mode` for the markdown file or not.

I forgot to say that I'm using doom-emacs in case that makes any difference.

**Comment by bdarcus** [comment]
Oops; that's my fault. This line shouldn't be there.

https://github.com/bdarcus/citar/blob/7651060551e3a3140be01848637d7190654fb87d/citar.el#L200

I should be able to fix it sometime today. 

You can test if it works if you add this to your config:

```elisp
(setq citar-major-mode-functions
  '(((org-mode) .
     ((local-bib-files . citar-org-local-bibs)
      (keys-at-point . citar-org-keys-at-point)))
    ((latex-mode) .
     ((local-bib-files . citar-latex-local-bib-files)
      (insert-keys . citar-latex-insert-keys)
      (insert-citation . citar-latex-insert-citation)
      (keys-at-point . citar-latex-keys-at-point)))
    ((markdown-mode) .
     ((insert-keys . citar-markdown-insert-keys))))))
```

**Comment by andrasbarany** [comment]
You have one `)` too many at the end but other than that this works. Thanks!

**Comment by bdarcus** [comment]
FYI, I'm hoping to include this in #366 today or tomorrow, and then will update the Doom PR 5290.
