### ISSUE TITLE
Binding `C-p` for `citar-org-update-pre-suffix` is disruptive

### ISSUE THREAD

**Issue by andersjohansson** [bdarcus/citar#369]
**Describe the bug**
When on an org citation with citar as activate-processor, `citar-org-citation-map` is active and `C-p`, bound to `citar-org-update-pre-suffix` shadows the standard binding for `previous-line`

**To Reproduce**
1. `(setq  org-cite-activate-processor 'citar)`
2. Leave point at an org citation
3. Attempt to call `previous-line` with `C-p`
4. `citar-org-update-pre-suffix` is called

**Expected behavior**
`C-p` should take me to the previous line 🙂.

I think the shadowing done by the other bindings in `citar-org-citation-map` are ok (that `C-k` kills citation instead of line is an improvement) but rebinding `C-p` breaks expectations quite harshly for those navigating by that means. I am not sure if there is any other very good or obvious binding.

**Comment by bdarcus** [comment]
What about C-n?

**Comment by bdarcus** [comment]
Here's the bindings that John used in org-ref-cite.

https://github.com/jkitchin/org-ref-cite/blob/102a853a678c57de43081bcf824917e2f7a8a4af/org-ref-cite-activate.el#L35

**Comment by bdarcus** [comment]
Forgot to link this in the commit, but I merged this just now.

https://github.com/bdarcus/citar/pull/366/commits/507a6b0749036ea59ed03e46502ec097c5b6d046

**Comment by andersjohansson** [comment]
Thanks! Much better 🙂
