### ISSUE TITLE
uniitialized error/warning in customize ui

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#371]
Why this, and how to fix?

![image](https://user-images.githubusercontent.com/1134/140568384-7996428b-ca55-42a8-8ff3-e41be874d082.png)

**Comment by minad** [comment]
Probably the :type is incorrect. You set the variables to nil but the type is 'function, which must not be nil. You can use `(choice function (const nil)` instead.

**Comment by bdarcus** [comment]
Except, many of those aren't functions.

In any case, I'll look into the types.

**Comment by minad** [comment]
I haven't looked closely but most :types exclude nil. For example also string.
