### ISSUE TITLE
Add markdown/pandoc keys-at-point function

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#376]
Syntax:

```
[prefix @key1 suffix; @key2]
```

But keys can also be bare:

```
@key3
```

I'm not good with regular expressions, but this seems to work:

```
"[\s\\[]@\\([[:word:]]+\\)"
```

Also, see this thread, which includes a suggestion for pandoc mode.

https://github.com/jrblevin/markdown-mode/issues/424

Which brings us to this defconst with the regex:

https://github.com/joostkremers/pandoc-mode/blob/bf01a14e99304653ae722226ea064c7d4b641774/pandoc-mode.el#L1490

```elisp
(defconst pandoc-regex-citation-key
  "\\(-?@\\([[:alnum:]_][[:alnum:]_:.#$%&+?<>~/-]*\\)\\)"
  "Regular expression for a citation key.")
```

![image](https://user-images.githubusercontent.com/1134/140608340-bd1bac3d-f3c9-443a-ae3f-6b4e4ad87202.png)

**Comment by bdarcus** [comment]
Closed with #379.

**Comment by ffsammak** [comment]
Wow! Syntax highlighting for markdown-mode citations in Emacs! Could you please elaborate on this method, after implementing your code? How would you specify the color for the 'pandoc-regex-citation-key'?

**Comment by bdarcus** [comment]
I don't really know; I just use pandoc-mode there and the doom one theme.
