### ISSUE TITLE
Can't see embark + install problem

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#380]
What key press or mouse click should I do to get the embark minibuffer displayed [here](https://github.com/bdarcus/citar#org-cite)?  

When I open an org file with a new-style org-cite link in it, like this [cite:@Stuart09missDatLargeDat, p. 11], then:

1. If I hover over the cite-link with a mouse, I see yellow popup with a formatted version of the appropriate bibtex entry
2. If I move the cursor over it, nothing happens in the minibuffer 
3. If I type `C-c o` on the link or mouse-click on hit, I'm brought to the appropriate entry in the bibtex file
4. If I type `M-x embark-dwim`, I get the error:  _"apply: Symbol’s function definition is void: citar-org-keys-at-point"_

I also have a strange install problem.  I use `use-package`  with `straight `always enabled:

`(straight-use-package 'use-package)`

and this means that I can install and configure `citar `like so:

```
(use-package citar
  :defer t
  :bind (("C-c b" . citar-insert-citation)
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset))
  :custom
  (citar-bibliography '("~/OneDrive/share/ref/energy.bib")))

;; use consult-completing-read for enhanced interface
;; From: https://github.com/bdarcus/citar
(with-eval-after-load 'embark
  (advice-add #'completing-read-multiple :override
              #'consult-completing-read-multiple))
```

However, this doesn't install `citar-org`; if I install it with the use package code here, emacs fails on startup, saying that it can't find `citar-org`.   So, I'm getting it like this:

```
(use-package citar-org
  :after (org citar)         ; so that org-mode-map is defined
 :straight (:host github :repo "bdarcus/citar") ; not on straight
  ;; melpa?
  :no-require
  :ensure nil
  :bind
  (:map org-mode-map ("C-c b" . #'org-cite-insert)) ; also  C-c C-x C-@
  :custom
  
  (org-cite-global-bibliography '("~/OneDrive/share/ref/energy.bib"))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-at-point-function 'embark-act)
  :init
  (citar-filenotify-setup '(LaTeX-mode-hook org-mode-hook)))
```

Even if I also point the `citar `use-package to your github repo, I still have to separately do the same `citar-org`.

This is all on GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26

Could you suggest a way that I could debug this?

**Comment by bdarcus** [comment]
This isn't really a bug; more just installation issues with straight.

Citar is a melpa package, and the recipe installs all the elisp files in the repo.

Citar-org should autoload as needed, and the only reason for the citar-org code in the README is to set the org-cite processors, so that it will in fact load load citar-org.

Have you tried setting the processors outside the citar-org block, and removing that?

**Comment by roshanshariff** [comment]
Hi @notuntoward,

I'm also using straight, and you should need only one change in your configuration. In the `use-package citar-org` block, use `:straight citar` to tell it that `citar-org` is part of `citar`.  Otherwise, since you have `straight-use-package-by-default` set, straight will try to install `citar-org` which is not a separate package. My configuration looks like this: 
```elisp
(use-package citar-org
  :straight citar
  :no-require
  :custom
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar))
```

You can also use `:straight nil` since you have a separate `use-package citar` block that will take care of installing citar, but it's safer to do it this way.

**Comment by notuntoward** [comment]
@bdarcus and @roshanshariff , thanks for the very quick replies.  I made the suggested change but embark still doesn't work.  But it doesn't work in a different way, so maybe that will make it more clear what's going on.

Here's my new (barely changed) setup:

```
(use-package citar
  :defer t
  :bind (("C-c b" . citar-insert-citation)
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset))
  :custom
  (citar-bibliography '("~/OneDrive/share/ref/energy.bib")))

;; use consult-completing-read for enhanced interface
;; From: https://github.com/bdarcus/citar
(with-eval-after-load 'embark
  (advice-add #'completing-read-multiple :override
              #'consult-completing-read-multiple))

;; org native citations
;; From: https://github.com/bdarcus/citar
(use-package citar-org
  :after (org citar)         ; so that org-mode-map is defined
  :straight citar
  ;; melpa?
  :no-require
  :ensure nil
  :bind
  (:map org-mode-map ("C-c b" . #'org-cite-insert)) ; also  C-c C-x C-@
  :custom
  
  (org-cite-global-bibliography '("~/OneDrive/share/ref/energy.bib"))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-at-point-function 'embark-act)
  :init
  (citar-filenotify-setup '(LaTeX-mode-hook org-mode-hook)))
```

Using it, the mouse and cursor still only send me to the correct .bib entry, without calling embark.  However, if I put the cursor in  a cite:link and type `M-x embark-act`, I get this error message:

`apply: Symbol’s function definition is void: citar-org-keys-at-point`

**Comment by roshanshariff** [comment]
Hmm, that is very strange. Can you try the following steps please?
1. Pull the latest version of Citar (`M-x straight-pull-package RET citar`) 
2. Rebuild Citar (`M-x straight-rebuild-package RET citar`)
3. Restart emacs

Also try removing the `:after (org citar)` line (it's not needed) and instead use the `:package org` argument to :bind:
```elisp
...
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)) ; also  C-c C-x C-@
...
```

**Comment by notuntoward** [comment]
Thanks.  Embark now pops up.
