### ISSUE TITLE
note opening doesn't work

### ISSUE THREAD

**Issue by jonathan-sahar-tau** [bdarcus/citar#384]
Hi,
This line from the readme doesn't work:
```(setq citar-file-open-note-function 'orb-citar-edit-note)```

There is no such variable, and no such function defined in the repo. (there is citar-open-note-function however, but nothing with orb and notes..)

thanks!

**Comment by bdarcus** [comment]
That was a query-replace mistake.

Seems they just merged a name change though, so should work if you update orb.

https://github.com/org-roam/org-roam-bibtex/commit/d65b70e9d19efc5001e01a61c36cc3e57e198131

Alternately, you can replace "citar" with "bibtex-actions".

**Comment by jonathan-sahar-tau** [comment]
thanks, should I replace it in both the variable and the function? Also, orb is updated and this still happens.

**Comment by bdarcus** [comment]
> thanks, should I replace it in both the variable and the function? 

Which function? 

In any case, you shouldn't need to change anything with an orb updae.

> Also, orb is updated and this still happens.

Shouldn't be the case. Did you restart Emacs?

**Comment by jonathan-sahar-tau** [comment]
I meant should I replace citar in ```orb-citar-edit-note``` as well.
I did restart emacs. should I have orb configured in some way, other that the basic ```use-package!```?

**Comment by bdarcus** [comment]
I just mean I think the README instructions should now be accurate with the orb update. So updating alone should have fixed it.

If not, paste your current config?

**Comment by jonathan-sahar-tau** [comment]
Thanks for looking at it. ATM, opening a note through embark does nothing.

```
(use-package! org-roam-bibtex
  :after org-roam
  :config
  (require 'org-ref)) ;
```

```
(use-package citar
  :no-require
  :custom
  (org-cite-global-bibliography (my/get-bib-file-list))
  (citar-bibliography (my/get-bib-file-list))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  ;; (citar-filenotify-callback 'refresh-cache)
  (citar-at-point-function 'embark-act)
  (citar-file-note-org-include '(org-id org-roam-ref))
  (citar-notes-paths literature-notes-dir)
  ;; optional: org-cite-insert is also bound to C-c C-x C-@
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert))
  :config
  (setq citar-file-open-note-function 'orb-citar-edit-note)
  (setq citar-templates '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
                                   (suffix . "${tags keywords keywords:*}   ${=key= id:15}    ${=type=:12}")
                                   (note . "#+title: Notes on ${author editor}, ${title}
* main points
* findings
* methods
* summary and short reference
* general notes
* see also (notes, tags/ other papers):
")))

  (setq citar-symbols
        `((file . (,(all-the-icons-icon-for-file "foo.pdf" :face 'all-the-icons-dred) .
                   ,(all-the-icons-icon-for-file "foo.pdf" :face 'citar-icon-dim)))
          (note . (,(all-the-icons-icon-for-file "foo.txt") .
                   ,(all-the-icons-icon-for-file "foo.txt" :face 'citar-icon-dim)))
          (link .
                (,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'all-the-icons-dpurple) .
                 ,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'citar-icon-dim)))))
;; Here we define a face to dim non 'active' icons, but preserve alignment
  (defface citar-icon-dim
    '((((background dark)) :foreground "#282c34")
      (((background light)) :foreground "#fafafa"))
    "Face for obscuring/dimming icons"
    :group 'all-the-icons-faces)

  (defun gen-bib-cache-idle ()
    "Generate bib item caches with idle timer"
    (run-with-idle-timer 0.5 nil #'citar-refresh))

  (add-hook 'LaTeX-mode-hook #'gen-bib-cache-idle)
  (add-hook 'org-mode-hook #'gen-bib-cache-idle)
  )
```

**Comment by bdarcus** [comment]
Do you get the error if you open an OR file _before_ using `citar-open-notes`?

**Comment by jonathan-sahar-tau** [comment]
I'm not getting an error at the moment, it just doesn't do anything.
I tried evaluating the setq now, but it didn't change the (non) behavior...

**Comment by bdarcus** [comment]
And if you remove the setq and use the default function?

**Comment by jonathan-sahar-tau** [comment]
> And if you remove the setq and use the default function?

same.

> You're not using doom; are you?

haha, I am actually.. why?

**Comment by bdarcus** [comment]
Because I would encourage you to use the biblio module PR, which is what i"m using ;-)

https://github.com/hlissner/doom-emacs/pull/5290

**Comment by bdarcus** [comment]
Is `literature-notes-dir` a list of paths?

**Comment by jonathan-sahar-tau** [comment]
it's a single path, a string.

> Because I would encourage you to use the biblio module PR, which is what i"m using ;-)

interesting! how do I enable it..? I didn't find it in init.el

**Comment by bdarcus** [comment]
> it's a single path, a string.

Should be a list.

```elisp
(setq citar-notes-paths (list "/path/to/notes/"))
```
 
> > Because I would encourage you to use the biblio module PR, which is what i"m using ;-)
> 
> interesting! how do I enable it..? I didn't find it in init.el

Under `tools` just `biblio`.

If you put the PR files in your local corresponding doom module directory, it should work.

**Comment by jonathan-sahar-tau** [comment]
Thanks. 
I'm not exactly sure how to do that, I've never worked with PRs before. Should I fetch-rebase a certain commit?

**Comment by jonathan-sahar-tau** [comment]
ah, looks like it was already there, since I'm on the develop branch. I'll check it out. Is there a guide to configure it?

**Comment by bdarcus** [comment]
The easiest way is just to download the PR package and config files to your local doom directory. Like for me:

```console
~/.config/doom/modules/tools/biblio/
```

> Is there a guide to configure it?

The PR includes a README.

**Comment by jonathan-sahar-tau** [comment]
I'm sorry for being slow on this - but I don't know how to download the PR files. from GH. I do have the biblio dir under modules/tools, since I've updated Doom, but I don't know where the README should be.

**Comment by jonathan-sahar-tau** [comment]
Hmm.. I've replaced the (use-package! citar...) block with:

```
(after! citar
  (setq! citar-bibliography (my/get-bib-file-list))
  (setq! citar-at-point-function 'embark-act)
  (setq! citar-file-note-org-include '(org-id org-roam-ref))
  (setq! citar-notes-paths literature-notes-dir)
  (setq! citar-library-paths bibliography-pdf-dir))
```
 Like the readme suggests  (they are all lists where they should be, I think)

It's still not working.. I see that ```org-cite-global-bibliography``` is not set as well.

**Comment by bdarcus** [comment]
Did you install the module files in the correct place, and add "biblio" to the init?

**Comment by jonathan-sahar-tau** [comment]
I did, and I do have biblio-* functions available through M-x

**Comment by bdarcus** [comment]
And you did `doom sync -u`?

Can you do `M-x toggle-debug-on-error`, then `M-x citar-open-notes`, and paste the results if you get an error?

**Comment by jonathan-sahar-tau** [comment]
> And you did doom sync -u?

I did.

Such voodoo..  the notes just works now, all of a sudden.

org-cite-insert still doesn't work though - both the weird minibufferand theh variable not being set. 
How does citar know it needs to set it once I ```(setq! citar-bibliography (my/get-bib-file-list))```?

**Comment by bdarcus** [comment]
You should see this, but probably the value is "basic":

![image](https://user-images.githubusercontent.com/1134/140928106-111c6064-e307-42b6-bf16-a1b80763c0e0.png)

What should happen is when you open an org buffer the first time, it should set the org-cite processor variables to citar.

**Comment by jonathan-sahar-tau** [comment]
yes, it's set to basic
