### ISSUE TITLE
citar-open shows a link to one too many papers

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#388]
In the attached org file, I'm linking to two papers, and when I run `M-x citar-open`, the initial minibuffer display shows an "L" next to one of them -- I'm assuming that "L" means that there's a link to this paper in the .org doc.  See the 1st screen shot.

If I search for the other paper in the org doc (by typing "stuart") I get a new minibuffer with an "L" next to the correct paper.  But there's also an "L" is next to the other paper, which actually isn't in the .org doc.  See 2nd screen shot.

Am I wrong about the meaning of "L"?

![image](https://user-images.githubusercontent.com/3851891/140878838-ff7efd2f-c76a-48b0-9676-096d39ae62bd.png)
![image](https://user-images.githubusercontent.com/3851891/140878878-3a1bf024-6ffe-4d0b-91c0-a19cccc4ea59.png)

[tmp_cite_test_org.txt](https://github.com/bdarcus/citar/files/7502753/tmp_cite_test_org.txt)

**Comment by bdarcus** [comment]
L just means there's a link (doi or url) associated with the reference, such that if you run open-link, it will open something.
