### ISSUE TITLE
Why not making 'citar-insert-citation' also works in org mode

### ISSUE THREAD

**Issue by duzaichuan** [bdarcus/citar#393]
I use latex, org for my writing and notes, and sometimes in markdown. So I would like to use 'citar-insert-citation' command in all these three scenarios. Also, it would be nice that the package can be lazy-loaded, triggered by 'citar-insert-citation', instead of loading after org mode.

Great package! Thanks for all you guys' contribution.

**Comment by christianramet** [comment]
Hi,

You can already do what you describe, if I understand you correctly. With either of the following configs, depending if you use `use-package` or not.

```
(with-eval-after-load 'org (require 'citar))
(with-eval-after-load 'markdown-mode (require 'citar))
```

```
(use-package citar
  :after (:any org markdown-mode latex-mode python-mode rst-mode)
  :config ...)
```

**Comment by bdarcus** [comment]
For now, at least, you use `org-cite-insert` for org.

I'm working on figuring out how to run that command through `citar-insert-citation` on #390, but it's not straightforward.

> it would be nice that the package can be lazy-loaded, triggered by 'citar-insert-citation', instead of loading after org mode.

Per @christianramet, this should already be the case.

**Comment by duzaichuan** [comment]
@christianramet @bdarcus Thanks for your replies. I should make it clearer that I already followed the REAME configs. What I want is running `org-cite-insert` through `citar-insert-citation` as  @bdarcus mentioned above. I will take a look at #390 .

**Comment by bdarcus** [comment]
> @christianramet @bdarcus Thanks for your replies. I should make it clearer that I already followed the REAME configs. What I want is running `org-cite-insert` through `citar-insert-citation` as @bdarcus mentioned above. I will take a look at #390 .

If you follow the discussion there, there are some decisions to make; it's not so straighforward.
