### ISSUE TITLE
no file opened when entry has more than one

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#398]
If an entry has only a single file associated with it, then citar can open its pdf; when I type C-o (f) on a cite link pointing to it, a pdf is opened.

However, if a bibtex entry has more than one file associated with it, citar doesn't open any of them; C-o (f) opens no files.  An example multiple file entry is shown below.  It seems to be in a standard format, as helm and JabRef can handle it.

```
@InProceedings{Habte19seriQC,
  author    = {Habte, Aron and Sengupta, Manajit and Andreas, Afshin and Xie, Yu},
  booktitle = {ICEM},
  title     = {Data {{Quality Assessment Using SERI}}-{{QC}}},
  year      = {2019},
  address   = {Denmark},
  abstract  = {High-quality solar resource data requires stringent calibration, operation and maintenance, and data quality assessment and control procedures. \textbullet{} Strict protocols for calibration, measurement, modeling, operation and maintenance, and data quality assessment and control are used at NREL. \textbullet{} NREL's SERI-QC software package is used to assess measurement data quality. \textbullet{} SERI-QC uses three component data analyses in the K-space, as shown in Figure 1.},
  comment   = {Does 3 component test.  

Does solar QC for the OpenSolar R and Python package (Feng19openSolarDat)

The manual came from here:
https://www.nrel.gov/docs/legosti/old/5608.pdf
and it has a flowshart of the original FORTRAN algorithm in section 6.3},
  file      = {:Habte19seriQC_poster.pdf:PDF:;:Habte19seriQC_slides.pdf:PDF:;:Habte19seriQC_manual.pdf:PDF:},
  groups    = {DealWith},
  language  = {en},
  ranking   = {rank1},
}
```

**Comment by bdarcus** [comment]
Have you updated in the past 24 hours?

If not, do; I included this parser in the default, which should parse that correctly?

https://github.com/bdarcus/citar/blob/0cee3c0d1180c7cb4938a8ddcca18a688b23d6c4/citar-file.el#L95-L100

Or can you set that parser variable yourself.

**Comment by notuntoward** [comment]
Yes, it's updated, and I have citar configured like shown below, but no pdf opens.  Could the problem be that I have the line `(citar-file-open-function 'citar-file-open-external)`:

*My citar config*
```
(use-package citar
;;  :defer t
  :bind (("C-c b" . citar-insert-citation)
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset))
  :custom
  (citar-bibliography '("~/OneDrive/share/ref/energy.bib"))
  (citar-library-paths '("~/OneDrive/share/ref/papers")))

;; use consult-completing-read for enhanced interface
;; From: https://github.com/bdarcus/citar
(with-eval-after-load 'embark
  (advice-add #'completing-read-multiple :override
              #'consult-completing-read-multiple))

;; org native citations
;; From: https://github.com/bdarcus/citar
(use-package citar-org
  :no-require
  :ensure nil
  ; citar-org is in citar: https://github.com/bdarcus/citar/issues/380
  :straight citar  
  :config
  (setq citar-file-parser-functions
        '(citar-file-parser-default
          citar-file-parser-triplet))
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)) ; also  C-c C-x C-@
  :custom
  (org-cite-global-bibliography '("~/OneDrive/share/ref/energy.bib"))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-at-point-function 'embark-act) ;; not strictly necessary
  (citar-file-open-function 'citar-file-open-external)
  :init
  ;; if .bib file changes, "invalidate the cache by default".  Is that good?
  ;; https://github.com/bdarcus/citar#refreshing-the-library-display
  (citar-filenotify-setup '(LaTeX-mode-hook org-mode-hook)))
```

**Comment by bdarcus** [comment]
> Yes, it's updated, and I have citar configured like shown below, but no pdf opens. Could the problem be that I have the line `(citar-file-open-function 'citar-file-open-external)`:

No. It looks like that syntax is slightly different.

```elisp
ELISP> (citar-file-parser-triplet "/" ":Habte19seriQC_poster.pdf:PDF:;:Habte19seriQC_slides.pdf:PDF:;:Habte19seriQC_manual.pdf:PDF:")
("/Habte19seriQC_poster.pdf:PDF" "/Habte19seriQC_slides.pdf:PDF" "/Habte19seriQC_manual.pdf:PDF")
```

Note how it doesn't strip off the `:PDF`.

What is the source of those files?

**Comment by notuntoward** [comment]
I don't remember anymore but my best guess is that it came from JabRef.  That's what I was mostly using at the time, and JabRef still it correctly now:

![image](https://user-images.githubusercontent.com/3851891/141382327-9abdc87e-63bd-4b4a-b6d2-9eae8177dcb2.png)

**Comment by bdarcus** [comment]
OK, I just merged a little change. Can you let me know if that works?

**Comment by notuntoward** [comment]
Thanks, that worked, although I had to remove `citar-file-parser-default` from this statement in my config:

```
  (setq citar-file-parser-functions
        '(citar-file-parser-default
          citar-file-parser-triplet))
```

You might of told me to do this before...

Anyway, as it stands, `citar` now opens all of the files in the bibtex `file` field.  That's functional, and enough for me, but similar software handles multiple files by popping up a menu, and allowing you to pick only the one(s) you want.   I'm happy as is.

**Comment by bdarcus** [comment]
> Thanks, that worked, although I had to remove `citar-file-parser-default` from this statement in my config:

Why? That would be a bug if so.

> Anyway, as it stands, `citar` now opens all of the files in the bibtex `file` field. That's functional, and enough for me, but similar software handles multiple files by popping up a menu, and allowing you to pick only the one(s) you want. I'm happy as is.

It's already there as option.

Read the manual (README)? 


The open commands are new, and may still change, including making the promoting default.

**Comment by notuntoward** [comment]
Turns out I was mistaken: it wasn't necessary to remove `citar-file-parser-default`.

About the multiple files menu:  Ahhh, now I see `citar-file-open-prompt`.  Thanks.  Also, it seems like most people would rather have that option turned on by default.

**Comment by bdarcus** [comment]
> Also, it does seem like most people would rather have that option turned on by default.

https://github.com/bdarcus/citar/commit/7de925f93fd3ee9cc92dc8a40506c1071fd3a23a
