### ISSUE TITLE
Allow link at start of org heading

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#399]
If I make a new org heading, and put the cursor just after the space following the last heading star, then `citar` won't create a link; if I type `C-c b`, I get this message: 

> user-error: Cannot insert a citation here

However, if I type a single visible character first, then `C-c b` works:

> Can do this:
> 
> * a [cite:@Kraskov04EstMutInfKNN]
> 
> Can't do this:
> 
> * [cite:@Kraskov04EstMutInfKNN]
> 

I've got an org file containing a couple thousand bibtex entries, most of them org-ref links starting one space after the last headline star -- are all of those illegal in the new syntax?

**Comment by bdarcus** [comment]
> ... are all of those illegal in the new syntax?

Yes, but it's possible it's an oversight. 

I vaguely remember a bug report about this on the org list, but I can't find it ATM.

In any case, I agree it looks like a bug to me; I encourage you to submit it to the org list.
