### ISSUE TITLE
citar-open-library-files returns a list with duplicate files

### ISSUE THREAD

**Issue by localauthor** [bdarcus/citar#402]
With `citar-file-open-prompt`set to 't', citar-open-library-files opens a completing-read prompt with duplicate files.

Oddly, the number of duplicates is a factor of the number of directories set in `citar-library-paths`: when set to nil or a single directory, each file is duplicated once (2 files listed); when set to two directories, each file is duplicated twice (4 files listed); three directories, 6 files listed.

I think I've narrowed it down to some of the iterating done in `citar-file-parser-default`. But that's as far as I've gotten. 

A sample bibtex entry:
```
@article{Wilson2004,
  title = {Foucault on the "{{Question}} of the {{Author}}": A {{Critical Exegesis}}},
  shorttitle = {Foucault on the "{{Question}} of the {{Author}}"},
  author = {Wilson, Adrian},
  year = {2004},
  month = apr,
  journal = {The Modern Language Review},
  volume = {99},
  number = {2},
  pages = {339},
  issn = {00267937},
  doi = {10.2307/3738750},
  langid = {english},
  file = {/Users/localauthor/Zotero/storage/LZULTBNK/Wilson2004 - Foucault on the Question of the Author A Critic.pdf}
}
```

**Comment by bdarcus** [comment]
That looks like a dumb bug that should be easy to fix.

**Comment by bdarcus** [comment]
I don't have time to test it, but just pushed a commit which should fix it.

Can you check and report back please?

**Comment by localauthor** [comment]
Didn't work. Moving `delete-dups` to `citar-file--possible-names` seems to fix it.
