### ISSUE TITLE
Repeats in file completion options when have two biblographies

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#407]
I get redundant file completion options when I configure citar for multiple .bib files, with one library path for each.  In other words, when I do `C-c o (f)`, I see the same pdf listed twice.  The path shown is correct, and it's to the only directory containing the pdf.

Also, is it possible to merge the two citar use-package statements?  As is, I've got duplicate database specs (`citar-bibliography` and `org-cite-global-bibliography`) and I'm not always sure which setting is important for general latex or org-mode e.g. `citar-library-paths`.

**The redundant completion options**

![image](https://user-images.githubusercontent.com/3851891/141656969-e494962b-5480-488e-b25f-11c522c1211c.png)

**My config**
```

(use-package citar
  :bind (("C-c b" . citar-insert-citation)
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset))
  :custom
  
  (citar-bibliography '("~/ref/energy.bib"
                        "~/ref/DOE_brainstorm/deepSolarDOE.bib"))
  (citar-library-paths '("~/ref/papers"
                         "~/ref/DOE_brainstorm/papers")))

;; use consult-completing-read for enhanced interface
;; From: https://github.com/bdarcus/citar
(with-eval-after-load 'embark
  (advice-add #'completing-read-multiple :override
              #'consult-completing-read-multiple))

;; org native citations
;; From: https://github.com/bdarcus/citar
(use-package citar-org
  :no-require
  :ensure nil
  ; citar-org is in citar: https://github.com/bdarcus/citar/issues/380
  :straight citar  
  :config
  ;; so citar can open JabRef-style file fields
  (setq citar-file-parser-functions '(citar-file-parser-default
                                      citar-file-parser-triplet))
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)) ; also  C-c C-x C-@
  :custom
  (org-cite-global-bibliography '("~/ref/energy.bib"
                                  "~/ref/DOE_brainstorm/deepSolarDOE.bib"))

  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-at-point-function 'embark-act) ;; not strictly necessary
  (citar-file-open-function 'citar-file-open-external)
  (citar-file-open-prompt t) ; open menu if entry has multiple attached files
  :init
  ;; if .bib file changes, "invalidate the cache by default".  Is that good?
  ;; https://github.com/bdarcus/citar#refreshing-the-library-display
  (citar-filenotify-setup '(LaTeX-mode-hook org-mode-hook)))

```

**Comment by bdarcus** [comment]
There were a couple of commits yesterday (see #402) that should have fixed this.

Have you updated today?

> Also, is it possible to merge the two citar use-package statements?

I don't know; am not an expert on use-package. 

Where do you think we stand on this @roshanshariff?

**Comment by notuntoward** [comment]
Yeah, I did update this a.m., but to no effect.  I guess it takes a while for changes to reach melpa.  

I do see the change after pointing `:straight` directly to the GitHub repo.  It works.  Thanks.

**Comment by roshanshariff** [comment]
The only reason there are two use-package blocks in the readme is to have a small configuration for people who only want to use Citar as an Org-Cite processor and nothing else. If you want to use both the "Basic" and "Org-Cite" configurations, then feel free to combine both of them into one block. Neither of the blocks run any code (just bind keymaps and/or set `:custom` variables) so it doesn't make any difference.

**Comment by notuntoward** [comment]
@roshanshariff, would it make sense, then, to merge the `citar-bibliography` and `org-cite-global-bibliography`?  This is just to avoid duplication.

**Comment by roshanshariff** [comment]
@notuntoward, you should set both the variables. The first one is what Citar considers a "global bibliography", available in any mode. The second one will be used by Org-Cite in org-mode files for operations not handled by Citar, like exporting the file. To minimize confusion, it's probably best that they both agree.
