### ISSUE TITLE
Including the reference key in a template

### ISSUE THREAD

**Issue by oatmealm** [bdarcus/citar#408]
In notes templates, using this example from the README, 

'''
note . "#+title: Notes on ${author editor}, ${title}")))
'''

I'd like to be able to include the reference key. I've tried including ${key} which doesn't seem to produce any content.

**Comment by bdarcus** [comment]
If you look at the default suffix template, you can see a hint: `${=key=}`.

**Comment by oatmealm** [comment]
10x. I tried it, in fact, and it didn't work originally for some reason. Now it does!
