### ISSUE TITLE
citar-library-paths is a possible pitfall

### ISSUE THREAD

**Issue by hpdeifel** [bdarcus/citar#409]
I'm going through the update from `bibtex-actions` to `citar`, including the move from `bibtex-completion` to hand-rolled variables. One of the changes I had to make in my init file was to set `citar-library-paths` instead of `bibtex-completion-library-path`. The plural instead of singular in the variable name is already quite a subtle difference, but easy to spot thanks to completion/`C-h v`/etc.

On the other hand, the type of this variable is now also changed from a single string (optionally a list) to requiring a list of strings. This was not obvious to me (despite the new name), but more more seriously, getting it wrong fails silently: Somehow, the code called from `citar-open-library-files` manages to never produce a type error and instead just return an empty list of files.

**Comment by bdarcus** [comment]
Yeah, good point.

But there's a wrinkle here.

I can add a check for the variable and signal an error when not a list. But what about people that store the file paths in the file field of their entries?
