### ISSUE TITLE
citar-file--possible-names broke

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#412]
Something isn't working correctly with this function now, which has cascading impacts (for example, open-notes now doesn't work correctly). It now only returns existing files, but should always return a list of paths.

```elisp
ELISP> (citar-file--possible-names "low2001" citar-notes-paths '("org"))
("/home/bruce/org/roam/biblio/low2001.org")
ELISP> (citar-file--possible-names "low200X1" citar-notes-paths '("org"))
nil
```

cc @localauthor @roshanshariff

**Comment by bdarcus** [comment]
The problem appears to be [here](https://github.com/bdarcus/citar/commit/92d165bc3f647a65a625e99fceb307fe48871a20#diff-d365c95862fe5c568f4020bef6ddb1cd248d9ea1804806448e82f5b23fb9f3a4R131); #413 should fix it, though I haven't tested it extensively.

**Comment by bdarcus** [comment]
OK @massdorp, I merged a fix. Can you test and confirm?

**Comment by maasdorp** [comment]
Thank you! Now it works as intended once again. I could create a new note from the template using citar-open-notes.

**Comment by roshanshariff** [comment]
Yes, sorry, my mistake. I hadn't realized how that function is used for creating new notes as well.

**Comment by bdarcus** [comment]
No worries; I should have caught that.
