### ISSUE TITLE
make citar-open-library-files open files without select for one candidate

### ISSUE THREAD

**Issue by tshu-w** [bdarcus/citar#414]
Hi, I'm frustrated at needing to confirm open file for `citar-open-library-files` even if there is only one candidates. It would much appreciated if you could make `citar-open-library-files` open files without select if there is only one candidate like `citar-open-notes`. Sorry, I'm busying recently and can only leave an issue with patch.
<img width="1887" alt="Screen Shot 2021-11-17 at 10 20 03" src="https://user-images.githubusercontent.com/13161779/142099688-9afb980c-71c7-4ff2-b26e-bf213fcd892d.png">

**Comment by bdarcus** [comment]
Yeah, good point. Done.
