### ISSUE TITLE
Make citar ignore JabRef line breaks "^M"

### ISSUE THREAD

**Issue by tasshein** [bdarcus/citar#418]
Citar does not display entries correctly when JabRef adds "^M" to break entries at the end of fields. Citar recongizes the faulty entries and it will add the references if selected, but the fields by which you can search your bibliography are not displayed, thus you cannot search these entries by title, keyword and so on.

What makes the case even more curious is that I can reproduce this error only on Windows 10. If I add entries on a machine running ArchLinux, "^M" is not added to the bib-file. It might be a JabRef problem, however as I cannot find any information on it on the internet, I suppose other completion tools ignore the code added by JabRef.

Here you can see what JabRef adds to the entries: 

![bib-entries](https://user-images.githubusercontent.com/71821836/142381040-46a435d8-5240-465c-9d5a-6de0358f7ecb.png)

Here you can see that citar sees the entry but ignores author, title and year:

![citar-entries](https://user-images.githubusercontent.com/71821836/142381225-fe78647f-f4da-4093-a497-396d4e457ac3.png)

I can reproduce this error on:
Windows 10
emacs 27.2
most recent version of citar
JabRef 5.4

**Comment by bdarcus** [comment]
This isn't a citar bug; it uses parsebib for parsing.

But seems likely your issue is something to do with JabRef and the files it's creating. Perhaps there's a config option there for line-endings?

**Comment by tasshein** [comment]
Thank you! That might be the solution I'm looking for!

**Comment by bdarcus** [comment]
I'm not sure, but you might try the default (Linux) newline separator here, and check the "reformat" option?

![image](https://user-images.githubusercontent.com/1134/142415962-d71eed77-bcda-45ca-aa6a-74d8c61ccff9.png)

I don't know how Emacs on Windows handles line endings though.
