### ISSUE TITLE
Make Citar not confused about notes

### ISSUE THREAD

**Issue by salutis** [bdarcus/citar#419]
I decided to start using notes with Citar, but I keep struggling to make it work.

I envision my BibTeX directory to have `org` files in it, such that it contains:

```
knuth-1984.bib   ; some bibliographic entry
knuth-1984.pdf   ; some library file associated with the bibliographic entry
knuth-1984.org   ; some bibliographic notes associated with the bibliographic entry
```

Thus, I configured Citar as follows:

```emacs-lisp
;; Make Citar find library files.
(setq-default citar-library-paths '("~/bib")
              citar-file-extensions '("pdf"
                                      "html"
                                      "epub"
                                      "txt"
                                      "png"
                                      "jpg"))

;; Make Citar find bibliographic notes.
(setq-default citar-notes-paths '("~/bib"))
```

Now, Citar seems confused, as it shows `N` for the items that have no (Org) notes.

P.S. I do not understand whether `citar-file-extensions` relates to the `library` or `notes` or both.

**Comment by bdarcus** [comment]
>  I do not understand whether citar-file-extensions relates to the library or notes or both.

Both.

The current design assumes notes are in a different directory than library files.

I could change that, but worry it might have unintended consequences.

**Comment by localauthor** [comment]
Would you restrict it by adding a `citar-note-extensions` variable/defcustom?

**Comment by bdarcus** [comment]
> Would you restrict it by adding a `citar-note-extensions` variable/defcustom?

Probably.

**Comment by localauthor** [comment]
Ok. I have a branch on my fork that does this. Not sure how much it would break configs to merge as is.

https://github.com/localauthor/citar/tree/note-extensions

**Comment by bdarcus** [comment]
Submit a PR? I doubt it would break anything.

You'd want to modify the default value for the current variable to exclude org, however.

Also, am not sure, but should it be singular extension? WDYT @salutis?

**Comment by localauthor** [comment]
Should the default value of `citar-file-extensions` `pdf` and `md`? Or should it just be `pdf`, and `md` be included in `org-note-extensions`?

**Comment by bdarcus** [comment]
> Should the default value of `citar-file-extensions` `pdf` and `md`? Or should it just be `pdf`, and `md` be included in `org-note-extensions`?

Good question.

I suppose we should think forward a bit.

Right now, there is only support for org notes.

But let's say someone wants to use markdown instead. How would that work? 

cc @roshanshariff

**Comment by localauthor** [comment]
As it is now, if someone wanted to use the`open-notes` function to open markdown files, they would have to write their own function to replace `citar-org-open-notes-default`, since that function hard-codes the org extension into it.

What would be the difference between `open-notes` and `edit-notes`?

**Comment by bdarcus** [comment]
> As it is now, if someone wanted to use the`open-notes` function to open markdown files, they would have to write their own function to replace `citar-org-open-notes-default`, since that function hard-codes the org extension into it.

Right, so aside from whether that's the right general design, it also points out that currently, this bit of code is only responsible for the display.
 
> What would be the difference between `open-notes` and `edit-notes`?

Nothing.

**Comment by localauthor** [comment]
Yes, formatting function is totally separate from the opening functions, such that they could pretty easily get misaligned (as @salutis has found).

**Comment by bdarcus** [comment]
Merged; we can continue to discuss the broader stuff here, if needed.

**Comment by salutis** [comment]
I have just updated, and all indicators now mach reality. Thank you @bdarcus and @localauthor!
