### ISSUE TITLE
Add "cursor here" marker to note templates

### ISSUE THREAD

**Issue by salutis** [bdarcus/citar#420]
I would like to specify where to put the cursor when creating new notes.

Consider the following `note` template:

```
#+title: ${title}
#+subtitle: Bibliographic Notes
#+author: Rudolf Adamkovič
#+email: salutis@me.com
#+latex_header: \setlength{\parindent}{4em}
#+latex_header: \setlength{\parskip}{1em}
#+property: header-args+ :comments link
#+cite_export: csl apa.csl

| ← PUT THE CURSOR HERE, INSTEAD OF TWO LINES BELOW "print_bibliography"

* References

#+print_bibliography:
```

**Comment by bdarcus** [comment]
I agree it makes sense, but am not sure how to do that ATM.

It might be that org-capture would be better suited to that, but I need to figure that out too.

**Comment by bdarcus** [comment]
@salutis - can you see what happens if you add `\?` to your template where you want point?

**Comment by salutis** [comment]
> @salutis - can you see what happens if you add `\?` to your template where you want point?

It prints `?`. The cursor remains elsewhere.

**Comment by bdarcus** [comment]
Are you using `org-roam`? `org-roam-bibtex`?

**Comment by salutis** [comment]
@bdarcus Nope. Org has enough bugs as it stands. 😄

**Comment by salutis** [comment]
Now that I think about it, I would like to specify a function that outputs the template. (As opposed to a string.) That way, I could inline the existing BibTeX file into Org `src` block, derive the BibTeX key (`(file-name-base buffer-file-name)`), and more.

**Comment by bdarcus** [comment]
> Now that I think about it, I would like to specify a function that outputs the template. (As opposed to a string.) That way, I could inline the existing BibTeX file into Org `src` block, derive the BibTeX key (`(file-name-base buffer-file-name)`), and more.

Is there anything stopping you from doing that now?

**Comment by salutis** [comment]
Oh, I see. I can set `citar-open-note-function` where I prepare the buffer.

**Comment by bdarcus** [comment]
Yes, you can write a note function to do whatever you want.

**Comment by salutis** [comment]
All right, it works. Thank you @bdarcus for your wise guidance!

For future readers, I wrote the following function:

```
#+name: bibliographic-entry-template
: #+title: %s
: #+subtitle: Bibliographic Notes
: #+author: %s
: #+email: %s
: #+property: header-args+ :comments link
: #+cite_export: csl apa.csl
:
: * Notes
:
: |
:
: * References
:
: #+begin_src bibtex :tangle %s :exports none
: %s
: #+end_src
:
: #+print_bibliography:
```

```emacs-lisp
#+begin_src emacs-lisp :var template=bibliographic-entry-template
(defun my-citar-org-open-notes (key entry)
  (let* ((bib (string-join (list my/bibtex-directory key ".bib")))
         (org (string-join (list my/bibtex-directory key ".org")))
         (new (not (file-exists-p org))))
    (funcall citar-file-open-function org)
    (when (and new (eq (buffer-size) 0))
      (insert (format template
                      (assoc-default "title" entry)
                      user-full-name
                      user-mail-address
                      bib
                      (with-temp-buffer
                        (insert-file-contents bib)
                        (buffer-string))))
      (search-backward "|")
      (delete-char 1))))

(setq-default citar-open-note-function 'my-citar-org-open-notes)
#+end_src
```

**Comment by bdarcus** [comment]
I added it the wiki here:

https://github.com/bdarcus/citar/wiki/Notes-configuration#org
