### ISSUE TITLE
citar-file-open does not offer all file resources associated with an entry when citar-file-extensions indicates multiple extensions 

### ISSUE THREAD

**Issue by oatmealm** [bdarcus/citar#436]
**Describe the bug**
Using the re-modeled `biblio` module for Doom (thanks!), when calling `citar-file-open` (explicitly or via `citar-dwim`) I'm only shown *.pdf resources, or probably only resources that are listed in the bibtex entery under `file`.

PS I'm not sure if this is the purpose `citar-library-paths`, so the following would be not expected to work.

**To Reproduce**
1. Update `citar-library-paths` to indicate where files reside
2. Update `citar-file-extensions` to support both pdf and org resources to be associated with a bibliography entry
3. Create a new bibtex entry i.e. in the global bibliography
4. Associate a PDF with it i.e. the file field would point to the pdf
5. Create an org file with the same name as the key used in the directory indicated by `citar-library-paths` but do not add it to the file field in the bib file

```
(after! citar
  (setq! citar-bibliography `(,+biblio-default-bibliography-files))
  (setq! citar-library-paths `(,+biblio-pdf-library-dir ,+biblio-pdf-ocr-library-dir))
  (setq! citar-notes-paths `(,+biblio-notes-path))
  (setq! citar-file-extensions '("pdf" "org"))
  ...
```

**Expected behavior**
When `citar-open-file` is activated it should display both the pdf and org files associated with a key.

**Emacs version:**
```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-09-29
- Framework: Doom
- Org: Org mode version 9.5 (9.5-??-73875939a @ /home/xxx/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: e418817
```

**Comment by localauthor** [comment]
Are you refreshing the cache after adding new files (via `citar-refresh`, for example)?

**Comment by oatmealm** [comment]
Yes. Refreshed manually and also restarted Emacs after 'doom sync' to make sure.

**Comment by bdarcus** [comment]
> I'm not sure if this is the purpose citar-library-paths, so the following would be not expected to work.

It _should_ work.

Taking a look at how `citar-file--possible-names` behaves with the key and an empty entry arg might be useful for figuring out what's going on.

**Comment by oatmealm** [comment]
It seems to see the files...

```
("/home/xxx/Nextcloud/Library/Garami2006.pdf" "/home/xxx/Nextcloud/Library/Garami2006.org" "/home/xxx/Nextcloud/references/ocr/Garami2006.pdf" "/home/xxx/Nextcloud/references/ocr/Garami2006.org")
```

**Comment by oatmealm** [comment]
No, holdon, it's the wrong key... double checking.

**Comment by bdarcus** [comment]
> Not sure what do you mean by "empty entry arg "...

Disregard; I was confusing with another function.

**Comment by oatmealm** [comment]
It seems `citar-file--possible-names` simply echos possible full paths...

**Comment by bdarcus** [comment]
The function I was thinking about was the related `citar-file--files-for-entry`, which checks if the possible files exist.

https://github.com/bdarcus/citar/blob/19d1af1c5f98469a2fa5e4066c2ef95a309222bf/citar-file.el#L156-L559

**Comment by oatmealm** [comment]
`(citar-file--files-for-entry "Garami2016" nil citar-library-paths citar-file-extensions)`

Returns just the pdf.

**Comment by bdarcus** [comment]
Hmm ... I can't see why that would be.

Any ideas @localauthor?

**Comment by localauthor** [comment]
No, I’m at a loss.

 I would use edebug, if you’re familiar with it, to step through `citar-file--files-for-entry` with those arguments and see what it returns when it loops through the org extension.

**Comment by oatmealm** [comment]
Ok, the debug made it clear it was looking at the wrong path for the org file. I've corrected that in it now works correctly.
Thanks and sorry, my bad. I should have checked it first.

![citar-open-file](https://user-images.githubusercontent.com/68159077/143074488-d66af6c8-079f-4837-b292-cfc82e6d722f.png)

**Comment by localauthor** [comment]
Good! Glad it’s working.
