### ISSUE TITLE
citar-insert-citation not exiting early on invalid major-modes

### ISSUE THREAD

**Issue by jethrokuan** [bdarcus/citar#441]
**Describe the bug**
A minor UX issue: `citar-insert-citation` follows through with the interactive selection, even though the major mode isn't supported.

**To Reproduce**
1. Open an emacs-lisp file (or any file not in a supported major-mode)
2. Run `citar-insert-citation`
3. Interactive prompts shows, and upon selection, we see:

```
Citation insertion is not supported for emacs-lisp-mode
```

**Expected behavior**
Running `citar-insert-citation` should exit immediately in unsupported major-modes.

**Emacs version:**
GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.5.2 (Build 20G95)) of 2021-11-22

**Comment by bdarcus** [comment]
> A minor UX issue: `citar-insert-citation` follows through with the interactive selection, even though the major mode isn't supported.

Yes, I've noticed that. I agree it's not ideal.

**Comment by bdarcus** [comment]
@minad - would it be fine to move the `citar-select-refs` line here to a `if-let*` block below, that first checks for the function?

https://github.com/bdarcus/citar/blob/715a026743d96da4121d596e497925098692bf6f/citar.el#L890-L900

**Comment by minad** [comment]
What about moving the unsupported check into the interactive specification? This seems to be the correct approach here.

**Comment by bdarcus** [comment]
I'll experiment a bit, but with first stab, I get a wrong type error ("listp") if I do that.

**Comment by minad** [comment]
~~~ elisp
(interactive (list (progn ...code...)))?
~~~
