### ISSUE TITLE
get entry for arbitrary bibtex/biblatex field

### ISSUE THREAD

**Issue by mclearc** [bdarcus/citar#444]
I'd like to be able to get the entry for an arbitrary field and run a function on that entry. In my case the field is the bookends (my macos ref manager) id#.

**Describe the solution you'd like**
I'd like to be able to run embark from the citar completion window on the entry and have it open the reference in bookends. This 
is a matter of running a particular bit of applescript on the entry in the `beref` field in the bibtex entry in my bib file. 

**Describe alternatives you've considered**
I've tried to hack something together in citar but it isn't working -- I am also not very good with elisp :(

**Comment by bdarcus** [comment]
So your immediate problem is getting the value for the field?

E.g. you want to do something like this?

```elisp
(citar-get-value "beref" entry)
```

...?

If yes, you can't do that, unless you include the field variable name in one of your templates, as the `citar--fields-in-formats` function pulls the fields from there, and feeds them to `parsebib-parse` to filter the results.

If that's the issue, we could add back a defcustom to allow this.

**Comment by mclearc** [comment]
Yes exactly -- a defcustom would be great, since I don't need to display this info in the display template.

**Comment by bdarcus** [comment]
OK, just merged a simple commit. Can you confirm that works?

**Comment by mclearc** [comment]
Yes that works -- thanks very much!
