### ISSUE TITLE
citar-insert-reference does not insert journal or publisher information

### ISSUE THREAD

**Issue by xcapaldi** [bdarcus/citar#447]
**Describe the bug**
`citar-insert-reference` inserts a formatted reference but it omits the journal or publisher information which is expected in the `preview` template defined in `citar-templates`.

**To Reproduce**
1.  Create a `.bib` file which you use as the reference source in citar. Ensure it includes a reference like this:

```BibTex
@article{wanunu-2012-nanop,
  author =       {Meni Wanunu},
  title =        {Nanopores: a Journey Towards Dna Sequencing},
  journal =      {Physics of Life Reviews},
  volume =       9,
  number =       2,
  pages =        {125-158},
  year =         2012,
  doi =          {10.1016/j.plrev.2012.05.010},
  url =          {https://doi.org/10.1016/j.plrev.2012.05.010},
  DATE_ADDED =   {Wed Oct 21 12:54:39 2020},
}
```

2. Invoke `citar-insert-reference` in the `*scratch*` buffer and select the entry in your bibtex file.
3. You should see the output like this: `Meni Wanunu (2012) Nanopores: a Journey Towards Dna Sequencing, .`

**Expected behavior**
`citar-insert-reference` should use the `preview` template in `citar-templates` which is defined as `(preview . "${author editor} (${year issued date}) ${title}, ${journal publisher container-title collection-title}.\n")`.
I expect the output should be something like: `Meni Wanunu (2012) Nanopores: a Journey Towards Dna Sequencing, Physics of Life Reviews.`

**Emacs version:**
27.2

**Comment by localauthor** [comment]
Try evaluating the following and refreshing the cache with `citar-refresh`.

```
(defun citar--fields-in-formats ()
  "Find the fields to mentioned in the templates."
  (seq-mapcat #'citar--fields-for-format
              (list (citar-get-template 'main)
                    (citar-get-template 'suffix)
                    (citar-get-template 'preview)
                    (citar-get-template 'note))))
```

**Comment by bdarcus** [comment]
> Try evaluating the following ...

As @localauthor suggests, was just a dumb little bug, now fixed.

And let us know WYT of the broader question of WTD with `citar-insert-reference`.

**Comment by xcapaldi** [comment]
Thank you @localauthor and @bdarcus 
It works perfectly now. I missed `citar--fields-in-formats` while I was glancing through the code.

As for WTD with `citar-insert-reference`, I personally have only a single use-case. I call it in the `*scratch*` buffer to generate a generic human-readable reference and then copy it into an external program to properly reference papers in presentations. Because of this, I don't really care that it adheres to any particular style. For me personally, it would probably be easier to use a function that just puts the formatted reference in the kill ring directly.
