### ISSUE TITLE
(user-customizable) Defaultable citation commands

### ISSUE THREAD

**Issue by Hugo-Heagren** [bdarcus/citar#452]
**Is your feature request related to a problem? Please describe.**
I often (almost always) use the same command for citations -- `\autocite`. It is frustrating to have to select this (especially as it is not the default) every time I insert a citation into a TeX buffer.

**Describe the solution you'd like**
1) Have a customizable variable, set to the default command to use for citations (in my case, the string `autocite`, `\autocite{%s}` or some such).
2) Allow users to customize (probably through some other variable, or perhaps the same one if it were handled cleverly) whether they would normally like to be prompted for a citation command by `citar-insert-citation`, or to always just use the default without prompting.
3) Add a prefix arg to `citar-insert-citation`, which would reverse the behaviour specified in 2 on a per-invocation basis.

**Describe alternatives you've considered**
No alternatives really, though this is a small QOL improvement, so that isn't particularly surprising.

**Additional context**
This is similar to a feature I suggest at karthink/consult-reftex#3, a somewhat similar project. As there, I would be happy to have a stab at implementing this and submit a PR.

**Comment by bdarcus** [comment]
Makes sense.

I know @aikrahguzar, who wrote the new latex stuff, typically only uses `\cite`, so would like appreciate.

>  I would be happy to have a stab at implementing this and submit a PR.

Please do.

The only suggestion I would make as you work on that is to keep in mind this project support multiple major modes. So you'll want to consider how the approach should work outside latex.

Also, if you can, you might play with the org support, which doesn't prompt for the style, though you can edit it by placing point in the right place.

Should the latex mode work the same?

**Comment by bdarcus** [comment]
BTW, on a [tangentially-related](https://github.com/bdarcus/oxr) point, can you post a screenshot of the consult-reftex ref insertation UI?

**Comment by Hugo-Heagren** [comment]
> BTW, on a tangentially-related point, can you post a screenshot of the consult-reftex ref insertion UI?

Sure.

![2021-12-02--19:01:34](https://user-images.githubusercontent.com/62905215/144486289-20a681ef-2d2a-4066-8bb6-7cd10145464f.jpg)

(I have [an issue](https://github.com/karthink/consult-reftex/issues/4) open about customising the categories, so that it recognises `ex` for example and so forth)

**Comment by Hugo-Heagren** [comment]
Gotta love a maintainer who replies fast!

> Please do.

Awesome. 

> The only suggestion I would make as you work on that is to keep in mind this project supports multiple major modes. So you'll want to consider how the approach should work outside latex.

Yes, this a good point. 

Markdown is simple because pandoc markdown doesn't support styles right (pandoc just uses an externally specified CSL sheet)? Though it [does](https://garrettgman.github.io/rmarkdown/authoring_pandoc_markdown.html#citations) support using `-` to suppress the author's name, which is pretty much just a tiny subset of the style functionality provided by LaTeX and org. Perhaps in markdown the arg should control whether the name is suppressed?

I'm still getting used to the vaguaries of org's (awesome) citation system, so I'll dig into it and try to do the most consistent thing I can. I'll keep you posted.

**Comment by bdarcus** [comment]
Here's what you get in org if point is within "cite", and you do `embark-act` and `i`:

![image](https://user-images.githubusercontent.com/1134/144488202-a8624630-f2fd-4426-9521-f2b226eb91b9.png)

So styles are not part of initial citation insertion, but a separate step.

**Comment by bdarcus** [comment]
PS - correct: pandoc doesn't have styles or commands.

**Comment by Hugo-Heagren** [comment]
> So styles are not part of initial citation insertion, but a separate step.

Interesting. Can I ask why? Like you say, it would be good to be consistent between org and LaTeX. Perhaps because org *has* a clear default style, whereas LaTeX doesn't?

**Comment by bdarcus** [comment]
The simple answer is because we're relying on some org machinery for that. So certainly there's room to rethink it; we could write our own.

But it seems sensible to me, and I'm not sure what a better approach would be.

Maybe your suggestion of using a prefix-arg to prompt for style or not as part of initial insertion would be an improvement; IDK.

cc @roshanshariff

**Comment by roshanshariff** [comment]
Regardless of any UI changes, I like the idea of having a buffer-local variable that specifies the default citation style. We could also provide a command to set this default for the current buffer, which would invoke a major-mode-specific style selection UI. Or you could set it as a file-local variable.

**Comment by bdarcus** [comment]
Also, there's related discussion elsewhere on this repo on finding a way for the latex mode to be smarter about bibtex vs natbib vs biblatex. That would be good to include too at some point.

**Comment by Hugo-Heagren** [comment]
> Regardless of any UI changes, I like the idea of having a buffer-local variable that specifies the default citation style. We could also provide a command to set this default for the current buffer, which would invoke a major-mode-specific style selection UI. Or you could set it as a file-local variable.

I like the idea of being able to change the default per-file. I don't think there would be many instances where setting it *just this once* would be useful (this is probably dealt with by the prefix arg on the insertion command), so I'm not sure how useful a command for that would be, but certainly setting it up in such a way that a standard emacs file/dir-variable would be very useful. I'll try to set it up that way.

**Comment by bdarcus** [comment]
Closed via #458
