### ISSUE TITLE
Export buffer citations to a bib or csl json file

### ISSUE THREAD

**Issue by pemocarlo** [bdarcus/citar#459]
**Is your feature request related to a problem? Please describe.**
I normally use a global bibliography file, but for some documents I prefer to only use a local citations source with the entries used there (e.g to share a standalone .tex + .bib with others)

**Describe the solution you'd like**
An interactive command to create a citations file containing only the entries in the current buffer

**Describe alternatives you've considered**
Keep a local bibliography file for specific documents, which is a hassle if you are already using a global one

**Additional context**

**Comment by bdarcus** [comment]
> An interactive command to create a citations file containing only the entries in the current buffer.

How would one set the output format with such a command? Would it prompt for that, for example? Also for a filename, perhaps with a reasonable default?

And presumably it'd work across the major-modes?

**Comment by pemocarlo** [comment]
Thank you @bdarcus for your reply!

> How would one set the output format with such a command? Would it prompt for that, for example? If yes, would that include the ability to convert among formats; for example, from bibtex to json?
Or would it simply copy from the global bib in whatever format that is (easier obviously)?

I would go with the second (easier) option, that would cover my use case.
Conversion is a nice utility, but maybe out of the scope of this package?

> Also for a filename, perhaps with a reasonable default?

Yes, great! :-)

**Comment by bdarcus** [comment]
> Conversion is a nice utility, but maybe out of the scope of this package?

Yes.

Note for me, or whoever implements this:

Functions to get the keys in a buffer:

1. latex: `reftex-all-used-citation-keys`
2. org: doesn't currently have one; `org-cite-list-keys` is limited to the export process (though I might ask about this)
3. markdown: doesn't exist

**Comment by localauthor** [comment]
Unless I'm missing something, it seems that `citar-markdown-list-keys` also accurately lists org-cite keys.

Maybe someone can confirm by testing out with the latest commit?  If you're using `citar-org`, you'll have to make sure `citar-markdown.el` is loaded first.

On that last point, if all works as expected in org, some complications arise with regard to ensuring the availability of necessary functions and variables. `citar-markdown-list-keys` and the defconst `citar-markdown-citation-key-regexp` are in `citar-markdown.el`, and users of `citar-org` functions might not have that file loaded.

Any elegant solutions come to mind?

**Comment by bdarcus** [comment]
The commit I just merged should address this.

I have not tested it yet (!), so let us know.

**Comment by localauthor** [comment]
Ok, narrowing it down. I'm having trouble getting  `citar-insert-bibtex` to work consistently.

When I restart my emacs session and load `citar` (main branch), `citar-insert-bibtex` consistently throws an error: "Wrong argument type: string-p, nil".

If I go into `bibtex.el` and run `eval-buffer`, then `citar-insert-buffer` works as expected. And, consequently, so does `citar-export-local-bib-file`.

Simply requiring `bibtex.el` in `citar.el` doesn't help. Can you reproduce any of this?
