### ISSUE TITLE
Another tiny typo?

### ISSUE THREAD

**Issue by apc** [bdarcus/citar#480]
I believe there's another typo in the README. I was looking to tweak the templates and started with what's [described](https://github.com/bdarcus/citar#templates) on the README as the default value of `citar-templates`: 

```
(setq citar-templates
      '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
        (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords:*}")
        (note . "#+title: Notes on ${author editor}, ${title}")))
```

But that contains an extra `#+title:`, which should be removed to avoid confusion. (I went down a deep rabbit hole trying to figure out why I was seeing the `#+title` bit in my list of org-roam nodes; only recently did I realize that the issue was a simple extra `#+title`!)

Thanks again for your work on this!

**Comment by bdarcus** [comment]
You know, it's probably quicker to just edit it yourself in the GitHub editing interface, and submit and a PR ;-)

If not, I'll get to it.

There's been a lot of changes recently, and sometimes the README doesn't keep up.

**Comment by apc** [comment]
Good point. Not quite used to submitting PRs but will keep that in mind.

**Comment by bdarcus** [comment]
With the GitHub edit interface, once you make the change, you can basically create the PR from the same place.
