### ISSUE TITLE
org-roam-bibtex notes don't show up in general in citar anymore

### ISSUE THREAD

**Issue by sm2n** [bdarcus/citar#485]
**Describe the bug**
I updated from an "old" (considering how fast development is) version of citar recently, from around July-August. Now when I open up citar's interface, bibtex entries that do have associated notes don't show it, even though I can select them to go to the notes. (i.e filtering on has:notes returns nothing). This is because citar has changed how it finds notes files, it now looks for files with a fixed filename scheme, which mine don't appear to follow since I keep my bibliographical notes in a subdirectory (`org/roam/bib/`), which works because org-roam doesn't care where you keep your stuff.

**To Reproduce**
1. M-x citar-open-notes
2. type has:notes

**Expected behavior**
Entries that have notes that can be opened through the interface should always be indicated.

**Emacs version:**
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26

**Additional context**
I patched this in my config with
```elisp
(defun citar-has-note ()
  (lambda (citekey _) (orb-note-exists-p citekey)))
```
This is obviously a hack though, so I'm wondering if there is a better way to do this.

By the way, thanks for all your work on citar! It's been a great help.

**Comment by bdarcus** [comment]
I'm not really sure what to tell you with the info you've provided.

Are your path variables correctly set?

**Comment by sm2n** [comment]
I wasn't aware there were path variables. Looking at the code, I assume you are talking about `citar-notes-paths`, and setting that to `'("~/org/roam/bib/")` fixed it. Thanks for the help. That said, I urge you to consider leaving the searching up to org-roam-bibtex when it is in use, as I feel that is more robust and requires less configuration. Especially since I believe org-roam-bibtex notes don't necessarily have to be files anymore, they can be any node in an org tree as of org-roam v2, though I'm not sure why you'd do that.

Some notes: https://github.com/bdarcus/citar/blob/7740300831af16f4c2bbc4012fcc6a21f1f9a809/citar.el#L890
This seems like a typo, `'citar-org-format-notes-default` should probably be `'citar-org-format-note-default`, the former doesn't exist, and so the condition is never true and the error never gets emitted. But even with that fix, there doesn't seem to be a message printed in my messages buffer when the condition is true. I'm guessing you can't print messages when you are already in the minibuffer or something similar.

**Comment by bdarcus** [comment]
> That said, I urge you to consider leaving the searching up to org-roam-bibtex when it is in use, as I feel that is more robust and requires less configuration. 

In the past, bibtex-actions had the same bibtex-completion dependency as orb, which is what both were using for this functionality. So it's not surprising they were consistent.

The current citar does not.

If you want to use both, then, you need to configure both,

But orb isn't required to integrate citar with org-roam. So the easy option is not to use orb ;-)

> This seems like a typo, `'citar-org-format-notes-default` should probably be `'citar-org-format-note-default`. The former doesn't exist, so the condition is never true, and the error never gets emitted. But even with that fix, there doesn't seem to be a message printed in my messages buffer when the condition is true. I'm guessing you can't print messages when you are already in the minibuffer or something similar.

I can look into that.

**Comment by bdarcus** [comment]
> I can look into that.

I just fixed this bug. Thanks!

**Comment by sm2n** [comment]
> In the past, bibtex-actions had the same bibtex-completion dependency as orb, which is what both were using for this functionality. So it's not surprising they were consistent.
> 
> The current citar does not.
> 
> If you want to use both, then, you need to configure both,
> 
> But orb isn't required to integrate citar with org-roam. So the easy option is not to use orb ;-)
Yeah, that makes sense. I wasn't aware org-roam integration was possible without orb though. In particular, do cite backlinks work? Is there an example configuration somewhere?

**Comment by bdarcus** [comment]
> In particular, do cite backlinks work? Is there an example configuration somewhere?

Yes. Org-roam now has support for org-cite, so if you use that, it should all work nicely, including backlinks, and embark integration at-point.

I don't believe you need to do anything special to make that work; the org-cite config on the readme should work.

**Comment by sm2n** [comment]
Ah ok. I take it that means I would have to rewrite all my org-ref format links to org-cite style links and the corresponding ROAM_REFS attributes?

**Comment by bdarcus** [comment]
> I take it that means I would have to rewrite all my org-ref format links to org-cite style links.

Yes, or convert them with code. See #442.

> ... and the corresponding ROAM_REFS attributes?

This I don't believe, since org-roam understands both.

**Comment by sm2n** [comment]
Thanks for the information. I'll have to try it out.

**Comment by notuntoward** [comment]
I also didn't realize that citar can replace org-roam-bibtex but am glad to
hear it.

It would be helpful if the citar README mentioned that, as well as the code
to convert org-ref links tot org-cite links.

**Comment by bdarcus** [comment]
> It would be helpful if the citar README mentioned that ...

What exactly would you propose that say?

Feel free to submit a PR ;-)

**Comment by bdarcus** [comment]
> What exactly would you propose that say?

Actually, can just make clear that org-roam supports org-cite, and the default org format note function will produce compatible files when using org-roam.

**Comment by bdarcus** [comment]
FWIW, last night, pandoc merged the start of org-cite support.

https://github.com/jgm/pandoc/commit/0679620f92ea880702cd46e680e837d6841dc3ec

You can use it to convert org-ref to org-cite like so:

```console
pandoc -f org -t org test.org 
```

**Comment by sm2n** [comment]
Haha, I already converted my stuff with consult-rg/embark/wgrep and some keyboard macros last night. But that's good to know anyway.

Org-cite is working pretty well so far, thanks for the tip. Reflinks and everything. My only gripe is that it seems that I can't have named cite links. i.e something like `[[cite:@allen09][The British Industrial Revolution in Global Perspective]]`.

**Comment by bdarcus** [comment]
> My only gripe is that it seems that I can't have named cite links.

No. But if you hover over a reference, you get a tool tip preview of it. And with a different activate processor, you could get different sorts of previews.

https://github.com/andras-simonyi/org-cite-csl-activate
