### ISSUE TITLE
Error inserting markdown citation

### ISSUE THREAD

**Issue by rsrock** [bdarcus/citar#499]
**Describe the bug**
When I try to insert a citation in a markdown document, I get the error `Wrong number of arguments: (1 . 1), 2`

**To Reproduce**
1. Visit a buffer in markdown-mode
2. Call `citar-insert-citation` through the `C-c b` binding
3. Select one or more citations, then hit return (<- I'm a new user of this package, is this what I should do here?)

When repeating the above but for latex or org buffers, I get more informative errors about my incomplete setup and other packages that I should install.

**Expected behavior**
Insert a citation like `[@foo]`

**Screenshots**
n/a

**Emacs version:**
27.2, macOS

**Additional context**
n/a

**Comment by bdarcus** [comment]
I see the same bug.

```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  citar-markdown-insert-citation(("huck1973d") nil)
  citar--major-mode-function(insert-citation #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_55> ("huck1973d") nil)
  citar-insert-citation((("huck1973d" ("title" . "Renegades") ("date" . "1973") ("author" . "Huck, Susan L.M.") ("=type=" . "article") ("=key=" . "huck1973d"))) nil)
  funcall-interactively(citar-insert-citation (("huck1973d" ("title" . "Renegades") ("date" . "1973") ("author" . "Huck, Susan L.M.") ("=type=" . "article") ("=key=" . "huck1973d"))) nil)
  command-execute(citar-insert-citation record)
  execute-extended-command(nil "citar-insert-citation" nil)
  funcall-interactively(execute-extended-command nil "citar-insert-citation" nil)
  command-execute(execute-extended-command)
```

cc @roshanshariff

**Comment by bdarcus** [comment]
Should be fixed with latest commit @rsrock.

**Comment by rsrock** [comment]
Thanks, that works.

**Comment by Hugo-Heagren** [comment]
> Is this perhaps related to #458, @Hugo-Heagren? I see the extra arg there.

Yep, this was my bad. Nice solution though, sorry I couldn't look at this myself, been a bit busy this week.
