### ISSUE TITLE
Embark snapshots do not include all data

### ISSUE THREAD

**Issue by salutis** [bdarcus/citar#504]
When I try to capture a snapshot (live or not) using Embark, it does not work well. The screenshot below shows the problem. 

**Expected:**

The top buffer (Embark snapshot) matches the bottom buffer (Citar).

**Actual:**

See the red arrows. They mark unexpected results.

<img width="1971" alt="Screen Shot 2021-12-26 at 20 10 08" src="https://user-images.githubusercontent.com/1158274/147418459-25ebc5e7-7ada-496a-8ede-74ae11a1838d.png">

**Comment by bdarcus** [comment]
I have no idea what could cause that, and doubt it could be anything in citar.

Are you sure it's not an embark issue?

**Comment by salutis** [comment]
I have no idea, but when I snapshot other buffers (such as files, buffers, or commands), the snapshots look normal.

**Comment by bdarcus** [comment]
@oantolin - any ideas what could cause this sort of behavior? I've no clue.

**Comment by oantolin** [comment]
No, no idea. Seems mysterious. My best guess is that no information is actually lost, just the display is being truncated. I'll try to reproduce it here.

**Comment by oantolin** [comment]
@salutis, if you act on one of the entries where stuff is missing, does the action seem to work and pick up all the data?

**Comment by bdarcus** [comment]
I can reproduce part of what @salutis sees; the `...` bits:

![image](https://user-images.githubusercontent.com/1134/147482742-f7caa53a-c84e-42ed-90f8-d7cede14ffcd.png)

But the rest of the displayed results look the same.

**Comment by oantolin** [comment]
I see both phenomena, the ellipsis and the void. I have no idea what's going on, but will look into it.

**Comment by oantolin** [comment]
It's something about the way Embark Collect buffer calculate the maximum width of a candidate. The width is being set too short and some entries get truncated. I'll keep digging.

**Comment by oantolin** [comment]
🤣 I just realized you tricked me into overriding my `consult-buffer`  key binding! Following the citar readme, I bound `ciatr-insert-citation` to `C-c b`. I will continue to investigate switching buffers with good old `switch-to-buffer`.

**Comment by oantolin** [comment]
Tabulated list mode does something odd with string that have invisible characters in them. Try this:

```elisp
(defun random-string (length)
  (number-to-string (random (expt 10 length))))

(completing-read
 "Prompt: "
 (cl-loop repeat 10
          collect (concat (random-string 6)
                          (propertize (random-string 200) 'invisible t)
                          (random-string 6))))
```

I'd expect Embark Collect to show the 12 visible digits in both grid and list view. When I tested it however, in grid view it does something weird: for every column but the last it shows only the first 6 digits even though the column is given width 13.

**Comment by bdarcus** [comment]
This is what I see, which is the same when using `embark-collect-snapshot`:

![image](https://user-images.githubusercontent.com/1134/147502998-465daf05-2118-4a23-99d3-affe01a5482e.png)

**Comment by oantolin** [comment]
Sure, in list view, but try the grid. I think list view would also show only 6 digits if I added an annotation to that example.

**Comment by oantolin** [comment]
OK, I think I fixed it. Please test!

**Comment by bdarcus** [comment]
> OK, I think I fixed it. Please test!

Looks good on my end.

@salutis?

**Comment by oantolin** [comment]
It's funny: Selectrum, Vertico and now Embark all implement their own function to simplify strings for presentation (that is, to remove invisible portions of strings and to substitute string portions that have a display property that is a string with the displayed strings). Maybe that's a reasonable feature request for Emacs. Relatedly, the `string-width` function should take into account invisible and display properties. cc @minad, @clemera.

**Comment by minad** [comment]
Yes, the `display-width` and `display-string` functions could well be added upstream. However upstream won't like this since we are using a simple implementation to achieve the flattening and we don't handle recursive properties etc. The general solution is more complicated and slower. At some point I asked upstream about this, but they were hesitant. If I recall correctly I asked for addtional arguments to `string-width` to avoid allocations and in that context also asked about a `display-width` function. I think the answer was that one should use the pixel string width computation (which is slow). `display-string` wasn't discussed.

**Comment by salutis** [comment]
> > OK, I think I fixed it. Please test!
> 
> Looks good on my end.
> 
> @salutis?

_Beautiful._ Thank you!

<img width="1472" alt="Screen Shot 2021-12-30 at 12 47 58" src="https://user-images.githubusercontent.com/1158274/147749302-9518b2a3-0a5c-4501-8e88-c8e82b179f44.png">
