### ISSUE TITLE
files field broke

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#505]
Perhaps an unintended consequence of #496, but file field parsing isn't working correctly ATM.

- the library display correctly shows an associated file
-  but when running `citar-open-library-file` or `citar-attach-library-file` then "no associated resources";f `citar-open`  works correctly however

**Comment by Yevgnen** [comment]
Got `embark PCH: (void-function citar-open-library-files)`

**Comment by bdarcus** [comment]
> Got `embark PCH: (void-function citar-open-library-files)`

This is a separate, dumb, bug, that'll fix on #509.
