### ISSUE TITLE
`citar-open` stopped working?

### ISSUE THREAD

**Issue by salutis** [bdarcus/citar#508]
I have just updated Citar and now, when I call `citar-open`, select some reference, and then select some related resource, I get:

```
funcall-interactively: Wrong type argument: listp, "/Users/salutis/bib/driscoll+2022.bib"
```

and 

```
funcall-interactively: Wrong type argument: listp, "/Users/salutis/bib/driscoll+2022.pdf"
```

Does `open-citar` work for you, folks?

**Comment by bdarcus** [comment]
Yeah, I see the error.

**Comment by bdarcus** [comment]
I fixed it on the linked PR, but will wait until tomorrow to merge it.

**Comment by bdarcus** [comment]
Not only is this now fixed, but there's some enhancements to try out.
