### ISSUE TITLE
Pause when inserting citation key in the first time

### ISSUE THREAD

**Issue by deshearth** [bdarcus/citar#510]
When I insert citation key in the first time, it will pause 1-2 sec. Is it normal? For inserting citation, it is fast though. After initial insertion, both are fast.

**Comment by bdarcus** [comment]
The first time you load citar (any command) can take a bit of time, depending on how large your file is. For my 767 item file, it takes less than a second.

Could that explain it?

**Comment by deshearth** [comment]
Yes. Thank you for the explanation.
