### ISSUE TITLE
Embark changed embark--ignore-target from a pre-action hook to a setup action hook

### ISSUE THREAD

**Issue by oantolin** [bdarcus/citar#512]
Currently citar does `(add-to-list 'embark-pre-action-hooks '(citar-insert-edit embark--ignore-target))`. But with oantolin/embark@5ebe2dfd91868ec525ea34ffd45941c5e9ce5358, `embark--ignore-target` has become something you need to put in `embark-setup-action-hooks` instead. (Sorry for changing it on you, I hope the double dash means you expected I might mess around with it.)

I'm not sure how closely you track embark versions. But once you depend on that commit you should change `pre-action` to `setup`. If you need to make citar work with embark versions before and after that commit you can use:

```elisp
(add-to-list (if (boundp 'embark-allow-edit-actions)
                 'embark-pre-action-hooks
               'embark-setup-action-hooks)
             '(citar-insert-edit embark--ignore-target))
```

Which works because that same commit removed the `embark-allow-edit-actions` variable.

**Comment by oantolin** [comment]
I didn't mean to label this a bug ... and I don't know how to change the label. 😆

**Comment by oantolin** [comment]
Sorry, new wrinkle: I'm renaming `embark-setup-action-hooks` to `embark-target-injection-hooks`.

**Comment by bdarcus** [comment]
Thanks @oantolin!

**Comment by oantolin** [comment]
Yes, the relevant commits are oantolin/embark@5ebe2dfd91868ec525ea34ffd45941c5e9ce5358 and oantolin/embark@82475bb826b21b90b3c61c1d7772ecddd136d870.

**Comment by bdarcus** [comment]
So I want this (though I need to check again if we even need this at this point)?

```elisp
(add-to-list (if (boundp 'embark-allow-edit-actions)
                 'embark-pre-action-hooks
               'embark-target-injection-hooks)
             '(citar-insert-edit embark--ignore-target))
```

**Comment by oantolin** [comment]
Yes, that's right, that code would work with Embark's both before and after that commit.

**Comment by bdarcus** [comment]
Done.

**Comment by bdarcus** [comment]
> ```emacs-lisp
> (add-to-list (if (boundp 'embark-allow-edit-actions)
> ```

Actually, @oantolin, this line is incorrect. Suggestion on the symbol name to check here?

**Comment by oantolin** [comment]
That's an odd error. When exactly do you get it? When loading citar?

**Comment by bdarcus** [comment]
> That's an odd error. When exactly do you get it? When loading citar?

No; when invoking `embark-act` from either buffer or minibuffer.

**Comment by oantolin** [comment]
I'd like to help but I can't reproduce it here, either in my personal configuration or from `emacs -q`. Here's what I tried: from `emacs -q` I ran this:

```elisp
(package-initialize)
(global-set-key (kbd "C-.") #'embark-act)
(require 'citar)
(setq citar-bibliography '("~/some-bib-file-I-have.bib"))
```

And then I used `M-x citar-insert-bibtex`, popped up the completions buffer and used `embark-act` on some of the entries there to open links and whatnot. Everything worked fine.

**Comment by bdarcus** [comment]
OK, I'll assume it's something with my local install. Thanks!

**Comment by oantolin** [comment]
Did you sort this out, @bdarcus?

**Comment by bdarcus** [comment]
Thanks for checking, but nope.

I'm pretty sure it's some weird thing with straight/doom, but I've yet to figure it out.

**Comment by bdarcus** [comment]
@oantolin - I'm still confused by this. I completely reinstalled doom, decided to declare `embark-allow-edit-actions` here, and I _still_ get this error in some cases (for example, calling `consult-line`).

```elisp
map-keymap: Symbol’s value as variable is void: embark-allow-edit-actions
```

**Comment by oantolin** [comment]
Well Embark no longer even has an `embark-allow-edit-actions` variable. So my first guess is that maybe Doom has pinned a recent enough version of Embark that the variable no longer exists, but some other Doom code still uses it. I'm really just guessing.

How did you declare it? A simple `(defvar embark-allow-edit-actions)` won't work because it leaves the variable void, you need to also assign a value to it, `(defvar embark-allow-edit-actions nil)`.

**Comment by bdarcus** [comment]
There's something wrong with doom that I can't figure out. No matter what, it checks out and installs the older pinned version, even if I unpin it, or pin it to the latest commit.

But I thought this code should work regardless of embark version?

**Comment by oantolin** [comment]
This is mysterious. I wonder where you are even using `embark-allow-edit-actions`. I'd suggest two things: (1) use `M-x toggle-debug-on-error` and run `consult-line` or any of the commands you still see the error for, the backtrace will reveal where the variable is being used; (2) just grep for it among your packages and configuration.

**Comment by oantolin** [comment]
> But I thought this code should work regardless of embark version?

This snippet?

```elisp
(add-to-list (if (boundp 'embark-allow-edit-actions)
                 'embark-pre-action-hooks
               'embark-setup-action-hooks)
             '(citar-insert-edit embark--ignore-target))
```

Yes, it should. I believe your problem is elsewhere.
