### ISSUE TITLE
Wrong type argument: listp <path/to/pdf> when using `org-open-at-point`

### ISSUE THREAD

**Issue by deshearth** [bdarcus/citar#515]
I get the same behavior as in #304. I still can't solve the problem after I read the issue.

**Describe the bug**
When using `org-open-at-point`, it says "wrong type argument: listp, <path/to/pdf>"

**To Reproduce**
1. cursor at cite key
2. `M-x org-open-at-point`

**Screenshots**

**Emacs version:**
GNU Emacs 28.0.90

**Additional context**

***some related commands
- directly run `M-x citar-open-library-file` works fine.
- run `M-x embark-act`
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/22242603/147785247-121e2c41-e3e2-4c41-ad12-545e68fe9767.png">
When I press `f`, it says
"Symbol's function definition is void: citar-open-library-files"

***My =citar= config
```
(use-package citar
      :bind (("C-c b" . citar-insert-citation)
             :map minibuffer-local-map
             ("M-b" . citar-insert-preset))
      :custom
      ;; org-cite only accepts list?
      ;;(org-cite-global-bibliography (list (expand-file-name "bib/ref.bib" bib-dir)))
      (citar-bibliography (list (expand-file-name "bib/ref.bib" bib-dir))) 
      (org-cite-insert-processor 'citar)
      (org-cite-follow-processor 'citar)
      (org-cite-activate-processor 'citar)
      (citar-library-paths (list (expand-file-name "lib" bib-dir))))
```
I don't know how to provide that bug report in #304.

**Comment by bdarcus** [comment]
Have you updated in the past day or so?

If, as I suspect, not, please do.

**Comment by deshearth** [comment]
I didn’t. Now I’ve updated it. It works perfectly. Thanks!
