### ISSUE TITLE
insert latex reference in org mode

### ISSUE THREAD

**Issue by fab6** [bdarcus/citar#525]
Hi

for my orgmode beamer presentation I am using a special macro to add `cite`s to the page on the lower left corner.
For this I am using the name `source`, e.g.
```
\newcommand{\source}[1]{\begin{textblock*}{4cm}(8.7cm,8.45cm)
    \begin{beamercolorbox}[ht=0.5cm,right]{framesource}
      \usebeamerfont{framesource}\usebeamercolor[fg]{framesource} Source: {#1}
    \end{beamercolorbox}
  \end{textblock*}}
```
and then I just put 
```
\source{somecite}
```
at the end of the slide; this works ok for some simple text but the export does not work with the org-citation.

The export works only from within a latex source, e.g.
```
#+BEGIN_EXPORT latex
\source{\cite{somecite}}
#+END_EXPORT
````

Though within this code region, it seems, that `citar` is not working as hoped.
I get for both functions `citar-insert-citation` and `org-cite-insert` the error `Cannot insert a citation here`

Maybe I am missing something or my `textblock` is not setup properly, but maybe there is already a simple way of dealing with this in `citar`!?

Thank you in advance!
Fab

**Comment by bdarcus** [comment]
> I get for both functions `citar-insert-citation` and `org-cite-insert` the error `Cannot insert a citation here`

Generally, when you see this error, it comes from org.

Except I'm confused: you're wanting to add a latex citation in those contexts; not org-cite?

**Comment by fab6** [comment]
thank you for your quick help!
yes, probably you are right, this would be the more clean and better approach (though it did not work with the special textbox during export, but this is not a problem for citar)
Thank you!
