### ISSUE TITLE
Citar disappeared from my system 

### ISSUE THREAD

**Issue by jonathan-sahar-tau** [bdarcus/citar#526]
Hi,
I'm on doom, with vertico and biblio.
I've upgraded doom and its packages, and citar no longer works - I don't even have any of its functions available under M-x.
I've tried to manually ```use-package!``` it, but I get ```no such file or directory citar```
Any ideas?

Thanks!

**Comment by bdarcus** [comment]
No; maybe something with your local doom install? Nothing's changed with the module (hasn't been bumped for a few weeks), so must be that.

**Comment by bdarcus** [comment]
> Nothing's changed with the module (hasn't been bumped for a few weeks), so must be that.

Actually, this is wrong, I just realized. Henrik bumped the tools modules yesterday.

Did you figure this out?
