### ISSUE TITLE
Access PDF from org-roam note

### ISSUE THREAD

**Issue by manueldeljesus** [bdarcus/citar#531]
Is it possible to access the PDF of a reference from its org-roam note? I am starting with Citar and Org-Roam and was thinking that it could be useful to be able to open the PDF of a reference from within the org-roam note. You may reach that note following some backlinks and would need to check something, like a figure.

I see that citar inserts the citekey int he org-roam note, so I could launch citar-open to look for the citekey and operate from there, but would be nice to have the option to directly access the PDF from the note.

Thank you very much for your help.

**Comment by bdarcus** [comment]
Right now, the org-cite follow processor (which provides this functionality) only works on org citations.

The `ROAM_REF` is not actually a citation, since org-cite citations aren't allowed in property drawers.

It _might_ be possible to extend this support to include that, but I'm not sure how straightforward that would be.

cc @roshanshariff

**Comment by manueldeljesus** [comment]
Thank you very much for your prompt and kind response.

**Comment by tshu-w** [comment]
@manueldeljesus Hi, I wrote a simple functions for this, and you can run it in org-roam note to call `citar-run-default-action`  for refs:
```emacs-lisp
  (defun org-roam-open-refs ()
    "Open REFs of the node at point."
    (interactive)
    (save-excursion
      (goto-char (org-roam-node-point (org-roam-node-at-point 'assert)))
      (when-let* ((p (org-entry-get (point) "ROAM_REFS"))
                  (refs (when p (split-string-and-unquote p)))
                  (refs (if (length> refs 1)
                            (completing-read-multiple "Open: " refs)
                          refs))
                  (user-error "No ROAM_REFS found"))

        (when-let ((oc-cites
                    (seq-map
                     (lambda (ref) (substring ref 1))
                     (seq-filter (apply-partially #'string-prefix-p "@") refs))))
          (citar-run-default-action oc-cites))

        (dolist (ref refs)
          (unless (string-prefix-p "@" ref)
            (browse-url ref))))))
```

**Comment by manueldeljesus** [comment]
Thank you *very* much @tshu-w. I was going to try to make a function myself to do this, although I was not very confident about my possibilities since I am very new to Emacs Lisp and I seem to be missing something about the language itself.

I will try to understand your functions to see if little by little I get Emacs Lisp to click in my head.

Again, your help is really appreciated.

**Comment by bdarcus** [comment]
If you want to just open the library files (PDFs and such), you can also just do:

```elisp
  (defun org-roam-open-refs ()
    "Open REFs of the node at point."
    (interactive)
    (save-excursion
      (goto-char (org-roam-node-point (org-roam-node-at-point 'assert)))
      (when-let* ((p (org-entry-get (point) "ROAM_REFS"))
                  (refs (when p (split-string-and-unquote p)))
                  (refs (if (length> refs 1)
                            (completing-read-multiple "Open: " refs)
                          refs))
                  (oc-cites
                   (seq-map
                    (lambda (ref) (substring ref 1))
                    (seq-filter (apply-partially #'string-prefix-p "@") refs)))
                  (user-error "No ROAM_REFS found"))

        (citar-open-library-files oc-cites))))
```

**Comment by tshu-w** [comment]
> Thank you _very_ much @tshu-w. I was going to try to make a function myself to do this, although I was not very confident about my possibilities since I am very new to Emacs Lisp and I seem to be missing something about the language itself.

Hi, I know little about elisp either, so I thought how I wrote this function may help you do this next time yourself. First I find this two functions [`org-roam-ref-add`](https://github.com/org-roam/org-roam/blob/master/org-roam-node.el#L1028), [`org-roam-db-insert-refs`](https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L494)  by search `org roam ref` related functions. Now that I knew how to get ROAM_REFS, things got easier and I kept searching how to handle it and finally finished the function above.

**Comment by manueldeljesus** [comment]
I need to get more used to reading Emacs Lisp. It takes me ages to wrap my head around what is trying to be done. Indeed, it took me some time to understand your function, but I think that I finally did (at least the last version) and it is working; thanks to both of you.

I have, however, three small doubts, so let me present them below:

1. The ```length>``` idiom was not working for me, so I changed it to a call of the ```>``` function over the result of ```(length refs)```. Was it originally a typo? Or is there something I am missing about the ```length>``` syntax?
2. @bdarcus implementation, which is the one that I ended up using, since what I want is to open the PDF, misnamed the function ```citar-open-library-file``` adding an s at the end, right?
3. The last part of the first version of the function, ```(dolist ...``` is supposed to open in a browser all the references in the ROAM note that are not citations (urls by default)?

Again, your help is really appreciated.

**Comment by bdarcus** [comment]
Oh yeah, there's some mistakes in that function, which I didn't test. I'll update it once I fix it.

**Comment by tshu-w** [comment]
> * The `length>` idiom was not working for me, so I changed it to a call of the `>` function over the result of `(length refs)`. Was it originally a typo? Or is there something I am missing about the `length>` syntax?

I have these functions defined in C source code. 
GNU Emacs 28.0.90 (build 1, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2021-12-22

<img width="939" alt="Screen Shot 2022-01-19 at 10 02 39" src="https://user-images.githubusercontent.com/13161779/150049704-824f20f7-cfdf-4256-a39e-0649a3c40900.png">

**Comment by manueldeljesus** [comment]
> I have these functions defined in C source code.

Understood. I was looking on the web to see if I was missing something in my Emacs installation and found nothing, thus the question.

**Comment by manueldeljesus** [comment]
> better error handling

I hope to be able to explore that aspect once that my Roam database increases in size and I start getting errors. For the moment it is very difficult for me to think in Emacs-Lisp without having an example to work with.

Thank you again for all your help.

**Comment by andersjohansson** [comment]
For the record, I thought modifying the `key-at-point` function was good enough for me. The function below additionally detects citation keys outside of org references. So if I navigate to the ref in an the properties drawer and invoke `embark-act`, I get the right actions suggested.

```emacs-lisp
(setf (alist-get
       'key-at-point
       (alist-get '(org-mode) citar-major-mode-functions nil nil #'equal))
      #'aj/citar-org-key-at-point)

(defun aj/citar-org-key-at-point ()
  "Return key at point for org-cite citation-reference."
  (or (when-let ((reference (citar-org--reference-at-point)))
        (cons (org-element-property :key reference)
              (cons (org-element-property :begin reference)
                    (org-element-property :end reference))))
      (when (org-in-regexp org-element-citation-key-re)
        (cons (match-string 0)
              (cons (match-beginning 0)
                    (match-end 0))))))
```

**Comment by andersjohansson** [comment]
Hi @manueldeljesus, sorry for being so brief in posting my code. But yes, you got it completely right. This function will be called when embark act is called (because `citar-key-finder` is added to `embark-target-finders` and that function will then call my function (as defined in `citar-major-mode-functions`).

Emacs and emacs-lisp is quite a ride, but it does help that it is so easy to lookup and inspect things. (M-x describe-function, the very good elisp info manual, edebug for stepping through execution)

**Comment by manueldeljesus** [comment]
No need to be sorry. I really appreciate that you shared your code and that you took the time to read and answer my question (the same recognition goes to @bdarcus and @tshu-w).

It's good also to have to use the tools of Emacs (describe-function and describe-variable) to "decipher" the codes you share. It is a much more interesting way to learn that to simply read the manual and try to do things. I will have have a look into ```edebug```, since that may also be really helpful to understand all the new codes.

Once again, thank you very much everyone.

**Comment by jkroes** [comment]
Seems like the core advantage of @bdarcus approach after correcting for errors in their code is that it can be used anywhere in the buffer; in contrast, @andersjohansson expands embark-act functionality when point is on a roam ref. Both have their own use cases. I just wish I knew how to omit the note itself from the multiple completion candidates with @bdarcus solution, since we're presumably already in the note.

**Comment by apc** [comment]
This discussion is very helpful. One question: would it make sense to adapt the functionality to also allow for calling any of the `citar-` functions when in `bibtex-mode`? It seems to me it would be convenient to be able to call e.g. `citar-open-library-file` when viewing a `.bib` file with point somewhere on the corresponding entry.

**Comment by tshu-w** [comment]
@apc I don't know whether citar have this feature now. `bibtex-completion` support this with this function:

```emacs-lisp
(defun bibtex-completion-get-key-bibtex ()
  "Return the key of the BibTeX entry at point, nil otherwise.
This function can be used by `bibtex-completion-key-at-point' to
find the key of the BibTeX entry at point in a BibTeX-mode
buffer."
  (when (eq major-mode 'bibtex-mode)
    (save-excursion
      (bibtex-beginning-of-entry)
      (and (looking-at bibtex-entry-maybe-empty-head)
           (bibtex-key-in-head)))))
```
and you can use `(citar-open-notes (list (bibtex-completion-get-key-bibtex)))` to open notes of the entry at point.

**Comment by apc** [comment]
Question for those in the know. Would the following be a good way to use `citar` functions on a `bibtex` file using Embark?  I'm not quite sure I understand everything  that's happening here, but it seems to work.

```elisp
(defun my/bibtex-key-finder ()
  "Return the key of the BibTeX entry at point, nil otherwise.
This function can be used by `bibtex-completion-key-at-point' to
find the key of the BibTeX entry at point in a BibTeX-mode
buffer.

Adapted from `bibtex-completion-get-key-bibtex'."
  (when (eq major-mode 'bibtex-mode)
    (save-excursion
      (bibtex-beginning-of-entry)
      (when-let (key (and (looking-at bibtex-entry-maybe-empty-head)
                          (bibtex-key-in-head)))
        (cons 'citar-key key)))))

(add-to-list 'embark-target-finders 'my/bibtex-key-finder)

```

**Comment by tshu-w** [comment]
> _EDIT_: I'm especially curious to know whether there's a way to remove some of the `citar` functions from the list of Embark actions when in a `bibtex` buffer (e.g. I have no need for `citar-open-entry` nor `citar-insert-edit` when in a `bibtex` buffer and would prefer to not even have the actions available when calling `embark-act` then).

Change `citar-citation-map` locally in `bibtex-mode`

**Comment by bdarcus** [comment]
I just stumbled on this again. Where does this stand?

Should we close it?

**Comment by manueldeljesus** [comment]
You solved the problem that I had, and on top of that, there were very interesting contributions. However, the original questions was solved, so I believe that it could be safely closed.
