### ISSUE TITLE
Calling `citar-insert-citation` in LaTeX files should not result in multiple commas

### ISSUE THREAD

**Issue by apc** [bdarcus/citar#533]
Start with point after the comma following the citation key: 

```tex
\cite{entry1,}
```

Call `citar-insert-citation` and select entry with key `entry2`. The expected result (and what we get using `reftex`) is

```tex
\cite{entry1,entry2}
```

Instead, what we get is 

```tex
\cite{entry1,, entry2}
```

I do not think the space after the comma is necessary nor ideal, but I do not know whether this is inconsistent with best practices. The double comma, though, seems like a bug. 

From what I can tell, the behavior is due to the way `citar-latex-insert-citation` is defined. Changing [this line](https://github.com/bdarcus/citar/blob/b24b5b94b7d5f6e7e96331b48a22e977e0013de1/citar-latex.el#L170) to 

```el
(unless (or (equal ?} (preceding-char)) (equal ?, (preceding-char))) (insert ", ")))
```

seems to deal with the problem, but I do not know whether this introduces unintended issues.

Running Emacs 28.0.90 on macOS.

**Comment by roshanshariff** [comment]
It looks to me like the text you started with, `\cite{entry1,}` already had the extra comma, which was preserved after calling `citar-insert-citation`? You wouldn't be able to get this result without manually typing an extra comma at some point, right?

**Comment by apc** [comment]
That is right @roshanshariff, but often I find myself adding the comma manually thinking I can quickly enter the next citation only to realize that I’m not sure, so I call `citar-insert-citation` and the rest is history. Also if I delete a citation I may sometimes leave the comma behind thinking I’m about to add another one anyway. I think I may have just gotten used to the way reftex works? Seemed like an easy and harmless fix but maybe I’m wrong!

**Comment by bdarcus** [comment]
> think I may have just gotten used to the way reftex works.

... which is a capf, accessed via company, for example?

**Comment by apc** [comment]
I was just using 'vanilla' `reftex-citation`, without company. I actually do not understand how `reftex-citation` works under the hood, it doesn't seem to make use of corfu, which is what I've been using for a little while.
