### ISSUE TITLE
Getting "Key not found" error when calling `citar-copy-reference`

### ISSUE THREAD

**Issue by apc** [bdarcus/citar#536]
Call `citar-copy-reference`, highlight an entry, and press RET. Expected a message of the form "Copied: ..." and a list of formatted references either in the kill-ring or the system clipboard. Instead, what I get is a "Key not found" error. I'm assuming this is a bug, but maybe I've misunderstood something?

Emacs version: 28.0.90. Citar version: v0.9-66-gb24b5b9

**Comment by bdarcus** [comment]
I can't reproduce that, either in org or in latex at point using embark, or directly in the minibuffer.

Am not sure ATM what to recommend, but will think about it.

**Comment by apc** [comment]
Maybe this will help?

```
Debugger entered--entering a function:
* clear-minibuffer-message()
* message("Key not found.")
* #f(compiled-function (keys-entries) "Copy formatted reference(s) associated with the KEYS-ENTRIES." (interactive #f(compiled-function () #<bytecode 0x1ffb733bf48a1>)) #<bytecode -0x154a455547ab69ae>)((("dorr2010-of" ("year" . "2010") ("title" . "Of Numbers and Electrons") ("author" . "Dorr, Cian") ("=type=" . "Article") ("=key=" . "dorr2010-of"))))
* apply(#f(compiled-function (keys-entries) "Copy formatted reference(s) associated with the KEYS-ENTRIES." (interactive #f(compiled-function () #<bytecode 0x1ffb733bf48a1>)) #<bytecode -0x154a455547ab69ae>) (("dorr2010-of" ("year" . "2010") ("title" . "Of Numbers and Electrons") ("author" . "Dorr, Cian") ("=type=" . "Article") ("=key=" . "dorr2010-of"))))
* citar-copy-reference((("dorr2010-of" ("year" . "2010") ("title" . "Of Numbers and Electrons") ("author" . "Dorr, Cian") ("=type=" . "Article") ("=key=" . "dorr2010-of"))))
  funcall-interactively(citar-copy-reference (("dorr2010-of" ("year" . "2010") ("title" . "Of Numbers and Electrons") ("author" . "Dorr, Cian") ("=type=" . "Article") ("=key=" . "dorr2010-of"))))
  call-interactively(citar-copy-reference record nil)
  command-execute(citar-copy-reference record)
  execute-extended-command(nil "citar-copy-reference" nil)
  funcall-interactively(execute-extended-command nil "citar-copy-reference" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by bdarcus** [comment]
Are you using the default `citar-format-reference-function`, or `citar-citeproc-format-reference`? I use the latter, so that might explain it if you're using the default.

**Comment by apc** [comment]
The default yes.

**Comment by bdarcus** [comment]
> The default yes.

That works fine for me also :shrug:.

**Comment by apc** [comment]
Hm. Any thoughts on what could be going on on my end? I'm still incapable of making much sense of backtraces...

**Comment by bdarcus** [comment]
I don't.

Any ideas @localauthor?

**Comment by localauthor** [comment]
I'm afraid I can't reproduce the problem either.

By any chance have you changed the default setting for `citar-templates`?

**Comment by apc** [comment]
I did, yes... maybe I wasn't careful when migrating my config after `bibtex-actions` became `citar`? Here's what I have as the value of `citar-templates`: 

```el
((main . "${author editor:15}   ${title:40}   ${date year issued:4}")
 (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords:*}")
 (note . "Notes on ${author editor}, ${title}"))
```

As you probably suspected, changing the value to the default suffices to get rid of the problem. And I guess the issue is that there's nothing associated with the 'preview' key, unlike in the default value?

**Comment by bdarcus** [comment]
> I guess the issue is that there's nothing associated with the 'preview' key, unlike in the default value?

Yes.

**Comment by apc** [comment]
That may be helpful, though I suspect my template was what it was because I'm a legacy user and maybe the analogue of `citar-templates` in `bibtex-actions` didn't have anything like that? 

Somewhat unrelated, it seems to me that the 'preview' key should be changed to take into account the fact that biblatex likes `journaltitle` and not `journal`. I'll create a mini PR which you're more than welcome to ignore 😜

**Comment by bdarcus** [comment]
FWIW, the citeproc option is worth trying if you use these functions a lot, and need support for different styles.

**Comment by localauthor** [comment]
> > I guess the issue is that there's nothing associated with the 'preview' key, unlike in the default value?
> 
> Yes.
> 
> Probably we should change the error message there @localauthor?

What about making `citar-get-template` a bit more talkative?

```
(defun citar-get-template (template-name)
  "Return template string for TEMPLATE-NAME."
  (let ((template
         (cdr (assoc template-name citar-templates))))
    (unless template
      (error "No template for \"%s\" - check variable 'citar-templates'" template-name))
    template))
```
