### ISSUE TITLE
citar cannot identify file path

### ISSUE THREAD

**Issue by Simon-Lin** [bdarcus/citar#542]
My bibtex entry has file field in the form
`{:path\to\file.pdf:pdf}`
and citar cannot seem to recognize this unless the second item is in all caps, i.e.
`{:path\to\file.pdf:PDF}`
Not sure if this is intended behavior or not, since in the previous version it seems to correctly identify the field names.

**Comment by bdarcus** [comment]
I don't believe anything changes with this code that would explain this. But I can take a look.

Did something else change with your emacs?

**Comment by Simon-Lin** [comment]
I recently updated my OS and the path of pdf viewer changed.
Changing the value of `citar-file-opening-function` to point to the correct path and restarting emacs solves the problem.
Not sure why it had to do with the capitalization of bibtex entry field but I no longer have this issue now.

**Comment by bdarcus** [comment]
> I recently updated my OS and the path of pdf viewer changed. Changing the value of `citar-file-opening-function` to point to the correct path and restarting emacs solves the problem.

So maybe really that binary just isn't on your system path? You shouldn't need to specify the full path for that function.

In any case, good you figured it out.
