### ISSUE TITLE
Automatically select sole candidate during multiple completion

### ISSUE THREAD

**Issue by jkroes** [bdarcus/citar#544]
citar provides `citar-open` to open links and files from a citation. This relies on multiple completion, but all of my bibliographic entries are associated with a single resource: a link or a file. Each time I invoke these commands, I have to `C-n` down from the input prompt to the sole resource to select it before confirming the selection. In contrast, `citar-open-library-files` can open a single file resource without multiple selection prompt, but is unable to handle URL resources. 

An ideal configuration for me would open both links and files without a prompt, or else would automatically select the sole candidate in the multiple completion prompt.

For context, I use vertico, consult, and embark. I could not find information on default candidate selection vis a vis consult's repository.

**Comment by bdarcus** [comment]
Some of "open" code does do that, but I guess not all. Makes sense for us to address that gap.

**Comment by localauthor** [comment]
This no-prompt behavior in `citar-open-library-file` used to be enabled by setting the variable `citar-file-open-prompt` to t, but that doesn't seem to be necessary anymore. That variable is still being defined, but I can't find it implemented anywhere...

Even so, I think the "no prompt if only one result" behavior should configurable, with a similar boolean defcustom, `citar-open-prompt` (which should be t by default). I often want to see what file or link is available before deciding if it's something I want to open.
