### ISSUE TITLE
Dependency on org-element

### ISSUE THREAD

**Issue by jgru** [bdarcus/citar#549]
Dear Bruce, 

first of all, thanks for providing the great pacakge `citar`. 
I have a remark regarding `citar`'s installation which has a dependency on `org-element` apparently.
 
If I install `citar` with the following `use-package`-snippet:
```elisp
(use-package citar
  :ensure t
  :after (tex org org-element)
  :bind (("C-c b" . citar-insert-citation)
	 :map minibuffer-local-map
	 ("M-b" . citar-insert-preset))
  :config
  ;; Use consult-completing-read for enhanced interface
  (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
  :custom
  (citar-library-paths '("~/pdfs/"))
  (citar-bibliography '("~/bibliography.bib")))
```
I get the following compilation-error on installation: 
```
Warning (bytecomp): the following functions are not known to be defined:
    org-element-parse-buffer, org-element-map
```
However, if `(use-package org-element)` is placed before the a/m `(use-package citar ...)` the compilation succeeds.
Is this known and intended or is it an issue (which maybe reside on my side)?

Best regards,
jgru

**Comment by bdarcus** [comment]
> Is this known and intended or is it an issue?

Neither; there shouldn't be a compile error. One of us will need to dig into this.

**Comment by jgru** [comment]
> Neither; there shouldn't be a compile error. One of us will need to dig into this.
Thanks for your reply.
Can I provide anything to help debugging?

**Comment by bdarcus** [comment]
No, that's OK. It's probably pretty straightforward; we may just need to declare those functions.

**Comment by bdarcus** [comment]
Actually, one thing you could try is to add this line to the top of `citar-org.el`, and remove the use-package declaration from your config, and confirm that works? If yes, you could submit a PR if you like.

```elisp
(require 'org-element)
```

**Comment by jgru** [comment]
> Actually, one thing you could try is to add this line to the top of `citar-org.el`, and remove the use-package declaration from your config, and confirm that works? If yes, you could submit a PR if you like.
> 
> ```emacs-lisp
> (require 'org-element)
> ```

Thanks for getting back to me. 
Strangely, HEAD of this repo and installing it via `package-install-file` succeeds flawlessly. 
No `(require 'org-element)` needed with this approach.

**Comment by bdarcus** [comment]
Do you want to close this then?
