### ISSUE TITLE
refresh before running insert-citation, automatically

### ISSUE THREAD

**Issue by steveb-123** [bdarcus/citar#555]
**Is your feature request related to a problem? Please describe.**
Over the course of a writing session I frequently update my bibliographic library (.bib file) with new entries through external software (zotero). Often I will add an item to my library, the .bib file gets updated immediately by zotero, then I will immediately cite it in my current document in emacs, by `M+x`, `citar-insert-citation`.

But, often citar does not display the newly-added entry when I search (`citar-insert-citation`), this is frustrating, but I run `citar-refresh` and it then is now there, and insertable.

**Describe the solution you'd like**
An option/setting where I can have `citar-refresh` automatically called before the `citar-insert-citation` chooser appears, so it's always up to date when I make selections. Alternatively a new function which is just a concatenation of refresh and insert citation.

Having it be an option (or a variant function `citar-refresh-and-insert` ?) would mean that while this overheard (the refresh) is small for me, for people with huge databases, or crappy computers, they won't pay a penalty in lag.

**Describe alternatives you've considered**
I can just manually run the refresh command *then* the insert citation command, but it breaks my writing flow even more.

**Additional context**
I'm accessing citar functions to enter bioliographic entries in `markdown-mode`.
I think I have citar installed via `(package! citar)`  in packages.el, along with the the `biblio` module, and `vertico` completion within the Doom emacs configuration framework.

PS thanks for citar it's awesome.

**Comment by bdarcus** [comment]
Can you take a look at [this section](https://github.com/bdarcus/citar#refreshing-the-library-display) of the README? That should cover your needs?

**Comment by steveb-123** [comment]
Thank you, I completely missed that somehow, it absolutely addresses my problem and was very clearly documented.

Adding the following to my `config.el` got me to where I needed to go.

```
(citar-filenotify-setup '(markdown-mode-hook LaTeX-mode-hook org-mode-hook))
```

I apologise for the mindless issue. Thanks for all the good work :)

**Comment by bdarcus** [comment]
No problem.
