### ISSUE TITLE
how to customize the display fields in the reference candidates selection UI?

### ISSUE THREAD

**Issue by RNAer** [bdarcus/citar#563]
I am wondering if there is any way to customize the fields shown in the screenshot after running insert citation (e.g. org-cite-insert) when using citar. For example, I'd like to show the journals of the publications.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/1000056/160148443-78fd9c1e-1cc5-4269-bea2-39f3b8c3a453.png">

**Comment by bdarcus** [comment]
Sure; see:

https://github.com/bdarcus/citar#templates

**Comment by RNAer** [comment]
Thanks, @bdarcus . I did customize the variable like below, but the display didn't have any change.
```

citar-templates is a variable defined in ‘citar.el’.

Its value is shown below.

Configures formatting for the bibliographic entry.

The main and suffix templates are for candidate display, and note
for the title field for new notes.

  You can customize this variable.

Value:
((main . "${author editor:30}        ${title:48}")
 (suffix . "          ${=type=:12}    ${tags keywords:*}")
 (preview . "${author editor}  ${journal journaltitle publisher container-title collection-title}.
")
 (note . "Notes on ${author editor}, ${title}"))
Original value was 
((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
 (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords keywords:*}")
 (preview . "${author editor} (${year issued date}) ${title}, ${journal journaltitle publisher container-title collection-title}.
")
 (note . "Notes on ${author editor}, ${title}"))
```

**Comment by bdarcus** [comment]
Do you run `citsr-refresh`, or restart emacs?

**Comment by RNAer** [comment]
Ah, didn't realize I needed to run citar-refresh. Now it works! Thanks a lot!

BTW, I see `main` and `suffix` are for the candidates display, and I guess`note` is for creating org or org-roam notes (?). What is the `preview` template for?

**Comment by bdarcus** [comment]
You can configure to auto refresh. See the docs.

Preview is for like copying full references.
