### ISSUE TITLE
Clarify parameters, docstring

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#571]
@roshanshariff, can you tell me what the docsting for this "default" parameter should be?

https://github.com/bdarcus/citar/blob/c94799e9f33e0645b5ac8696e19bdc9328d7cb7e/citar.el#L459-L460

Also, now that I think about it, "key" isn't very self-explanatory, nor that the parameter "key" results in a returned "key".

In short, can we clarify this?

_Originally posted by @bdarcus in https://github.com/bdarcus/citar/issues/570#issuecomment-1097908899_

**Comment by roshanshariff** [comment]
Maybe the docstring should be something like:
```
Return function associated with KEY in 'major-mode-functions'. If no function is found matching KEY for the current major mode, return DEFAULT.
```

**Comment by bdarcus** [comment]
Thanks. But what is KEY then?

A named function type?

**Comment by roshanshariff** [comment]
Maybe something like "a function implementing the functionality named by KEY for the current major mode"? And a reference to the `major-mode-functions` docstring for the list of valid keys?

**Comment by bdarcus** [comment]
I actually ended up going with your original recommendation. Thanks.
