### ISSUE TITLE
doom embark-act bug

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#576]
I consistently get this error when using doom (though not with vanilla test script) when trying to involve `embark-act` from either buffer or minibuffer. 

Can you intrerpet this error message @oantolin, or have any guesses what could cause it?

```elisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (citar-run-default-action citar-insert-keys citar-copy-reference citar-insert-reference citar-insert-citation citar-insert-bibtex))
  boundp((citar-run-default-action citar-insert-keys citar-copy-reference citar-insert-reference citar-insert-citation citar-insert-bibtex))
  (if (boundp embark-multitarget-actions) (progn (if (member #'bd/search-pdf-contents embark-multitarget-actions) embark-multitarget-actions (setq embark-multitarget-actions (cons #'bd/search-pdf-contents embark-multitarget-actions)))))
  (lambda nil (if (boundp embark-multitarget-actions) (progn (if (member #'bd/search-pdf-contents embark-multitarget-actions) embark-multitarget-actions (setq embark-multitarget-actions (cons #'bd/search-pdf-contents embark-multitarget-actions))))))()
  eval-after-load-helper("/home/bruce/.config/emacs/.local/straight/build-29...")
```

**Comment by oantolin** [comment]
I think it's just a typo, the third line of your message starts with:

    (if (boundp embark-multitarget-actions)

It should have a quote in front embark-multitarget-actions:

    (if (boundp 'embark-multitarget-actions)

(You want to ask if the symbol naming the variable is bound, not if the *value* of the variable is in turn bound to something else.)

I'm guessing that code is somewhere in your personal configuration, because it does something with a bd/search-pdf-contents.

**Comment by bdarcus** [comment]
> I'm guessing that code is somewhere in your personal configuration, because it does something with a bd/search-pdf-contents.

Yes!

And that explains why it worked fine outside doom!

Thanks!

**Comment by oantolin** [comment]
Glad to hear that fixed it!
