### ISSUE TITLE
Question: why is citar not finding my PDF files?

### ISSUE THREAD

**Issue by roryk** [bdarcus/citar#578]
I had citar working with export from Paperpile fine, but I can't figure out how to get citar to see PDF files after switching to Zotero.  For example, in my `Papers.bib`:

```
@article{li_engineering_2020,
	title = {Engineering adeno-associated virus vectors for gene therapy},
	volume = {21},
	issn = {1471-0056},
	url = {http://dx.doi.org/10.1038/s41576-019-0205-4},
	doi = {10.1038/s41576-019-0205-4},
	abstract = {Adeno-associated virus (AAV) vector-mediated gene delivery was recently
approved for the treatment of inherited blindness and spinal muscular
atrophy, and long-term therapeutic effects have been achieved for other
rare diseases, including haemophilia and Duchenne muscular dystrophy.
However, current research indicates that the genetic modification of AAV
vectors may further facilitate the success of AAV gene therapy. Vector
engineering can increase AAV transduction efficiency (by optimizing the
transgene cassette), vector tropism (using capsid engineering) and the
ability of the capsid and transgene to avoid the host immune response (by
genetically modifying these components), as well as optimize the
large-scale production of AAV.},
	number = {4},
	journal = {Nat. Rev. Genet.},
	author = {Li, Chengwen and Samulski, R Jude},
	month = apr,
	year = {2020},
	keywords = {Patch},
	pages = {255--272},
	file = {Li and Samulski 2020 - Engineering adeno-associated virus vectors for gene therapy:files/1491/Li and Samulski 2020 - Engineering adeno-associated virus vectors for gene therapy.pdf:application/pdf},
}
```

I can see notes, open the DOI, etc. But the PDF doesn't show up as a resource with `citar-open` and there are no options with `citar-open-library-file`:
 
The file exists:

```
'files/1491/Li and Samulski 2020 - Engineering adeno-associated virus vectors for gene therapy.pdf'
```

My citar configuration:

```emacs-lisp
(setq! citar-bibliography '("/Users/rory/Zotero/Papers/Papers.bib"))
(setq! citar-notes-paths '("/Users/rory/Documents/Org/roam/notes/"))
(setq citar-symbols
      `((file ,(all-the-icons-faicon "file-o" :face 'all-the-icons-green :v-adjust -0.1) . " ")
        (note ,(all-the-icons-material "speaker_notes" :face 'all-the-icons-blue :v-adjust -0.3) . " ")
        (link ,(all-the-icons-octicon "link" :face 'all-the-icons-orange :v-adjust 0.01) . " ")))
(setq citar-symbol-separator "  ")
```

Thanks so much for making `citar`, Bruce!

**Comment by bdarcus** [comment]
Am not sure, but perhaps because those aren't complete file paths?

**Comment by roryk** [comment]
Thanks for the super fast response! I swapped that one to be the full path and did `citar-refresh` but still no dice.

**Comment by roryk** [comment]
Ok, I figured it out! Zotero is putting `:` as the delimiter, but the `citar-file-parser-default` wants ;. I swapped that one to `;` and it works with that parser. I added the Calibre style parser in but that doesn't seem to parse what Zotero is doing correctly.

**Comment by roryk** [comment]
This might have been a change in the new version of Zotero that was recently released-- I can push a PR for another parser to do this one.

**Comment by bdarcus** [comment]
> This might have been a change in the new version of Zotero that was recently released-- I can push a PR for another parser to do this one.

It may be that you can just modify the default one to use either `;` or `:`, similar to how the "triplet" one accepts two different delimiters.

In any case, take a look at the README section on this, and please update that along with the code :-)

https://github.com/bdarcus/citar#files-file-association-and-file-field-parsing

**Comment by bdarcus** [comment]
One followup question here: is this a Zotero thing, or a Better BibTeX thing?
