### ISSUE TITLE
Problem with citar-inser-citation

### ISSUE THREAD

**Issue by lazzalazza** [bdarcus/citar#580]
When evoked, citar-insert-citation doesn't open a list of possible candidates as it used to do before the last update but only a "Reference:" entry. On pressing tab after a sequence of chars, a list of candidates appears, but selecting one doens't lead to the insertion of the citation, giving an "Aborted" message instead.

I dont' know if this new behaviour of the citar-insert-citations command is wanted, but I would gladly go back to the list (which is still accessible calling other commands such as citar-open-notes, etc.). Would there be a way to go back to this kind of behaviour?

**To Reproduce**
1. Exectute citar-insert-citation
2. Start typing the name of an author
3. Press tab
4. Select from the list of candidates
5. The selected candidate is inserted after "Reference:"
6. Press enter
7. "Aborted" message

emacs version: 28.0.91
citar version: 20200423.1738

**Comment by bdarcus** [comment]
Can you post a screenshot?

**Comment by lazzalazza** [comment]
Sure!
<img width="737" alt="Schermata 2022-04-25 alle 19 57 35" src="https://user-images.githubusercontent.com/60494153/165146983-d76fa168-243c-42ed-87ba-023a5bcb106a.png">
<img width="737" alt="Schermata 2022-04-25 alle 19 57 47" src="https://user-images.githubusercontent.com/60494153/165147053-2deae1c5-9b33-45de-8343-da668372d011.png">
<img width="1055" alt="Schermata 2022-04-25 alle 19 58 02" src="https://user-images.githubusercontent.com/60494153/165147086-328c3665-aa62-46d1-803a-7ff8c0bc1b16.png">
<img width="1055" alt="Schermata 2022-04-25 alle 19 58 13" src="https://user-images.githubusercontent.com/60494153/165147106-c5847aeb-8c5e-4765-bbb3-f881bd1c2e58.png">
<img width="1512" alt="Schermata 2022-04-25 alle 19 58 24" src="https://user-images.githubusercontent.com/60494153/165147128-c3a27485-e027-468d-8dab-1401c1059654.png">
<img width="657" alt="Schermata 2022-04-25 alle 19 58 34" src="https://user-images.githubusercontent.com/60494153/165147144-3207457e-2589-4807-a866-7fcfa02df9d3.png">

**Comment by bdarcus** [comment]
I still don't really understand, and think I need more info.

I don't see any issues with either `citar-insert-citation` or `org-cite-insert` (which is really what you should use in org).

Just to take a guess.

I recently made this commit, which changes default to use CRM.

https://github.com/bdarcus/citar/commit/8c820ced36d5d0ce8149eea384e29dd21c3d3057

Are you wanting that nil?

I will say that CRM works much better with citar using `completing-read-multiple`.

**Comment by lazzalazza** [comment]
Yep, I wanted that nil... If I change it back to nil it works perfectly.

Otherwise, if I select the entry I need and press enter twice, there is no way to insert the citation, ending with an "Aborted" message. The exact same happens with org-cite-insert. What should I do to select the right entry and complete the reference if I keep "citar-select-multiple t"?

**Comment by bdarcus** [comment]
By default `consult-completing-read-multiple` expects you to use enter to select and then enter again to finish.

E.g. to enter only one candidate, you hit enter twice.

But I have it configured (and I think it's now configured in Doom) so that you can select with `TAB`, and complete with `RET`. See:

https://github.com/bdarcus/citar/issues/492#issuecomment-997024450

**Comment by lazzalazza** [comment]
The problem is exactly this: hitting enter twice does not work!

**Comment by bdarcus** [comment]
I'm not sure how to reproduce that then. It might have something to do with your config.

Do you get an error, or just unexpected results?

If the former, can you turn on `toggle-debug-on-error` and post any results?

**Comment by bdarcus** [comment]
FWIW, I just tested this with the script in the `test' directory, using `consult-completing-read-multiple`, and it worked as expected.

**Comment by bdarcus** [comment]
Oh wait, @lazzalazza, are using helm as your completion engine?

**Comment by lazzalazza** [comment]
Yes, sorry, I should have mentioned that!

**Comment by bdarcus** [comment]
I'd guess that may be the issue; some incompatibility between helm and CRM.

I use and recommend vertico and embark, FWIW. Citar is optimized for that ecosystem; not helm or ivy.
