### ISSUE TITLE
Running citar functions returns `Method ‘C’ is not known.`

### ISSUE THREAD

**Issue by grszkthfr** [bdarcus/citar#581]
*This is likely a configuration issue/bug. However, the error message is so generic, that I have trouble finding my way to it's source.*

**Describe the bug**

Running citar functions (e.g. `citar-insert-citation` or `citar-open-entry`) returns

```
Method ‘C’ is not known.
tramp-error: Method ‘C’ is not known.
```

**To Reproduce**

Admittedly, I am having also trouble getting `citar`to work it in an `emacs -Q` session.
What I tried so far: install `citar` and latest `org-mode` and setting ` (setq org-cite-global-bibliography '("~/references.bib"))` as well as `  (setq citar-bibliography '("~/references.bib"))`. However, their seems to be still some unmatched dependecies... 
I had the problem on Ubuntu 18.04 as well as on the latest 22.04. So, I suspect an error in my [config](https://gitlab.com/grszkthfr/dotfiles/-/blob/master/emacs/.emacs.d/init.el#L731-741).

**Expected behavior**
Work as described in the README. :-)

**Emacs version:**

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2022-01-24, modified by Debian

**Comment by bdarcus** [comment]
Hmm ... I've never seen an error like that. Any ideas why it's related to tramp?

Also, when you say you can't even get it running with emacs -q, does that include with the bundle test script (see "test" dir)?

Do note that the org-cite processors should be set here to "citar".

**Comment by grszkthfr** [comment]
> Hmm ... I've never seen an error like that. Any ideas why it's reported as related to tramp?

No ideas, never used it, it was never installed...

> Also, when you say you can't even get it running with emacs -q, does that include with the bundled test script (see "test" dir)?

No, I used the `package-install` dialoge... Now I've run it within the test-dir, and it returns `eval-buffer: Cannot open load file: No such file or directory, oc`

> And can you say more on "unmatched dependencies"?

I tried avoiding a rabbit hole, probably to early. :-) It gave me the same error that `oc` is missing... 
 
> Do note that the org-cite processors should be set here to "citar".

Yep, this are left overs of an earlier attempt to find the issue...

**Comment by bdarcus** [comment]
> No such file or directory, oc.

This means there's an issue with the org install; oc is the org-cite module.

Perhaps you have an older version of org installed?

**Comment by grszkthfr** [comment]
> Perhaps you have an older version of org installed?
>
> EDIT: from looking at your config, it seems you're using straight for installing org? If yes, I think it should be up-to-date.
>

I think so: Org mode version 9.5.2 (9.5.2-gd80aa2 @ /home/gkh/.emacs.d/straight/build/org/)
 
> What happens if you do `(require 'oc)` or `(fboundp 'org-cite-insert)` in ielm?

In my private config:
`(require 'oc)` returns `oc`
`(fboundp 'org-cite-insert)` returns `t`

In emacs -Q (from run.sh in test-dir):
org-version: 9.3
`(require 'oc)` returns 

```
Debugger entered--Lisp error: (void-variable oc)
  (require oc)
  eval((require oc) t)
  eval-expression((require oc) nil nil 127)
  funcall-interactively(eval-expression (require oc) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

`(fboundp 'org-cite-insert)` returns `nil`

**Comment by bdarcus** [comment]
So the Q version isn't installing and loading the correct org version.

Your private config is, but I have no idea why you'd be getting a tramp-related error; I've never seen that.

Do any citar commands work without that error?

FWIW, here's what I have on my doom-based install, but I think your version should still work fine:

```console
Org mode version 9.6 (9.6-??-58eb3e7894 @ /home/bruce/.config/emacs/.local/straight/build-29.0.50/org/)
```

**Comment by bdarcus** [comment]
Also, what happens if you do `M-x org-cite-insert` in an org buffer?

**Comment by grszkthfr** [comment]
> Also, what happens if you do `M-x org-cite-insert` in an org buffer?

That works, it is only related to `citar-*` functions...

> Do any citar commands work without that error?

Basically, no. I haven't tried all, but all `citar-open-*`and `citar.insert-*` and also commands such as `citar-refresh` or `citar-cop-references`.

**Comment by bdarcus** [comment]
> That works, it is only related to `citar-*` functions...

"works" when `org-cite-insert-processor` is set to citar? As in, it's calling a citar function, and presenting the citar UI?

Or you're using basic?

The tramp thing is super strange, since you don't even have it configured, and your bib file is local on your machine; right?

**Comment by bdarcus** [comment]
Maybe this thread is helpful?

https://emacs.stackexchange.com/questions/59679/emacs-cannot-start-from-spotlight-method-zsh-is-not-known

**Comment by grszkthfr** [comment]
Wow! I had only one function available: `tramp-unload-tramp`, but that did the trickt and `citar` works! :tada: 

What a *thing*, that also survived the transfer to another machine!

Anyways, thanks for your help, and the package. Now I can finally take advantage of it. :-)
