### ISSUE TITLE
citation key insert capf redux

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#592]
Awhile back I added a capf, but wasn't happy with it; it was either too greedy, so that it activated when it shouldn't, or it was too strict, so that it didn't activate at all.

So I removed it.

Going back to look at this again, and with a bit of help from @mclearc, I finally figured it out!

This works with org-cite, then:

```elisp

(defun citar-complete-key-at-point-org-cite ()
    "Complete org-cite citation key at point."
      (let ((element (org-element-at-point)))
        (when (or (eq 'citation (org-element-type (org-element-context element)))
                  (and (or (eq ?@ (char-before))
                           (looking-back org-element-citation-key-re
                                         (line-beginning-position)))
                 (let ((origin (point)))
                   (save-excursion
                     (and (re-search-backward org-element-citation-prefix-re
                                              (org-element-property
                                               :begin element)
                                              t)
                          (not (search-forward "]" origin t)))))))
          (let* ((candidates (citar--get-candidates))
                 (begin (save-excursion (backward-word) (point)))
                 (end (point)))
            (list begin end candidates
                  :exit-function
                  (lambda (str _status)
                    ;; take completion str and replace with key
                    (delete-char (- (length str)))
                    (insert (cadr (assoc str candidates)))))))))
```

And the result:

![image](https://user-images.githubusercontent.com/1502422/168179714-4206dca6-9b00-46f2-8829-d5504dcc20b3.png)
![image](https://user-images.githubusercontent.com/1502422/168179778-2622970a-149e-4041-b3aa-0e36a818e7dd.png)

So questions:

1. Should I add this back then?
2. If yes, how? Does it go in a new `citar-capf.el`? And how do we generalize it for use with the other major modes? Or do we even need to?

**Comment by mclearc** [comment]
I'm happy to try and see if I can figure this out by using some of the strategy of company-bibtex. This is the key bit of code i think:

```emacs-lisp
    (prefix (cond ((derived-mode-p 'latex-mode)
		   (company-grab (format "%s\\(%s,\\)*\\(%s\\)"
					 company-bibtex-latex-citation-regex
					 company-bibtex-key-regex
					 company-bibtex-key-regex)
				 2))
		  ((derived-mode-p 'org-mode)
		   (company-grab (format "%s\\(%s,\\)*\\(%s\\)"
					 company-bibtex-org-citation-regex
					 company-bibtex-key-regex
					 company-bibtex-key-regex)
				 2))
		  ((derived-mode-p 'markdown-mode)
		   (company-grab (format "%s\\(%s\\)"
					 company-bibtex-pandoc-citation-regex
					 company-bibtex-key-regex)
				 1))
```
So use `cond` to check mode and then a regex. But I'll have to screw around with it a bit.

**Comment by bdarcus** [comment]
It seems that the regex stuff (which is the bit recommended by Nicolas, who wrote org-cite, and is a core org developer) relies on three regexs:

1. the prefix to the citation-reference (in org, it's "[cite:")
2. the prefix for the key ("@")
3. the suffix for the citation (for org, "]").

That ensures it only activates within a citation.

Not sure that approach works in the other modes.

**Comment by bdarcus** [comment]
Quick question: how do you get it to insert?

I get the pop-up with corfu, but hitting `RET` does not insert.

I wonder if it might be another evil conflict?

**Comment by mclearc** [comment]
> Quick question: how do you get it to insert?

I have tab mapped to `corfu-insert`

> I wonder if it might be another evil conflict?

Maybe? I don't use evil anymore so I can't say for sure.

**Comment by mclearc** [comment]
This is working ok for org and markdown but not TeX. It seems like the problem is with regex. Any ideas?

```emacs-lisp
(defun capf-citar ()
  "Complete citation key at point for org, markdown, or latex."
  (let ((element (org-element-at-point))
        (capf-citar-latex-regex "\\(?:cite\\(?:\\(?:[pt]\\*\\|[pt]\\)?{\\)\\)\\([[:alnum:]_-]*,\\)*\\([[:alnum:]_-]*\\)")
        (capf-citar-markdown-regexp (concat "-?@"                         ; @ preceded by optional -
                                            "\\(?:"
                                            "{\\(?1:.*?\\)}"              ; brace-delimited key
                                            "\\|"
                                            "\\(?1:[[:alnum:]_][[:alnum:]]*\\(?:[:.#$%&+?<>~/-][[:alnum:]]+\\)*\\)"
                                            "\\)")))
    (when
        (cond
         ((and (derived-mode-p 'org-mode)
               (or (eq 'citation (org-element-type (org-element-context element)))
                   (and (or (eq ?@ (char-before))
                            (looking-back org-element-citation-key-re
                                          (line-beginning-position)))
                        (let ((origin (point)))
                          (save-excursion
                            (and (re-search-backward org-element-citation-prefix-re
                                                     (org-element-property
                                                      :begin element)
                                                     t)
                                 (not (search-forward "]" origin t)))))))))
         ((and (derived-mode-p 'markdown-mode)
               (or (eq ?@ (char-before))
                   (looking-back capf-citar-markdown-regexp
                                 (line-beginning-position)))))
         ((derived-mode-p 'latex-mode)
          (looking-back capf-citar-latex-regex 2)))
      (let* ((candidates (citar--get-candidates))
             (begin (save-excursion (backward-word) (point)))
             (end (point)))
        (list begin end candidates
              :exit-function
              (lambda (str _status)
                ;; take completion str and replace with key
                (delete-char (- (length str)))
                (insert (cadr (assoc str candidates)))))))))


(add-hook 'completion-at-point-functions
          #'capf-citar
          'append)
```

**Comment by bdarcus** [comment]
> This is working ok for org and markdown but not TeX. It seems like the problem is with regex. Any ideas?

No. But pinging @aikrahguzar, in case he has any (he wrote the latex stuff).

**Comment by mclearc** [comment]
Cool - also: I was thinking of possibly making this a stand-alone capf package. Or would you prefer to just see it as part of citar? Either way works for me. 

--
Colin McLear
Associate Professor
Department of Philosophy 
University of Nebraska–Lincoln
colinmclear.net

**Comment by bdarcus** [comment]
> I was thinking of possibly making this a stand-alone capf package. Or would you prefer to just see it as part of citar?

No. I like the idea of a standalone package.

**Comment by aikrahguzar** [comment]
> ```emacs-lisp
> (add-hook 'completion-at-point-functions
>           #'capf-citar
>           'append)
> ```

I don't have much of an idea since my regex-foo is non-existent and I haven't looked much at capfs but given that you are (very likely) putting it at the end of `completion-at-point-functions` some other capf might be activating first without providing any candidates. Have you tried removing all other tex capfs?

P.S. I think the usual way of adding capfs is buffer locally, so something like,
```emacs-lisp
(defun citar-capf-hook () (add-hook 'completion-at-point-functions #'citar-capf nil t))
(add-hook 'latex-mode-hook #'citar-capf-hook)
```
This way you can also define a few functions that are more specific instead of matching on `major-mode` in the capf body.

**Comment by mclearc** [comment]
looks like the regex was fine -- it was that the completion-at-point function was getting overridden by the other latex capf. So it looks something like

```emacs-lisp
  (defun capf-citar-hook () (add-hook 'completion-at-point-functions #'capf-citar -100 t))
  (add-hook 'tex-mode-hook #'capf-citar-hook)
  (add-hook 'markdown-mode-hook #'capf-citar-hook)
  (add-hook 'org-mode-hook #'capf-citar-hook)
```

Ideally I'd like to make this dependent only on paresbib rather than on citar itself. But we'll see how that goes. Otherwise the function should work ok -- would be good if you can test it and see.

**Comment by bdarcus** [comment]
Wouldn't it be `citar-capf` rather than `capf-citar`?

> Ideally I'd like to make this dependent only on paresbib rather than on citar itself.

To avoid a dependency, or for some other reason?

To remove the dependency, I think you'd need to recreate code to create the candidates (the parsebib hash likely won't do), do caching, and figure out which file(s) to load.

Citar actually does quite a bit here, including buffer-local vs global caching and such.

You may also be able to make it configurable somehow.

**Comment by mclearc** [comment]
> Wouldn't it be citar-capf rather than capf-citar?

yeah -- I've just been sloppy in switching around the names, but if I end up keeping the dependency on citar then `citar-capf` will be the namespace. 

>To avoid a dependency, or for some other reason?

To avoid the dependency if it can be done neatly with just parsebib, since there may be people who want a capf for bibtex but don't use citar. this would make it the capf parallel of `company-bibtex`. But maybe that's not necessary and unnecessarily duplicates functioning that is already in citar.

**Comment by bdarcus** [comment]
Actually, I just tried it, and can't get it to work, in either latex or org. I only ever get a "no match".

**Comment by mclearc** [comment]
> Actually, I just tried it, and can't get it to work, in either latex or org. I only ever get a "no match".

is it showing up in buffer local variable `completion-at-point-functions`?

**Comment by bdarcus** [comment]
I think I was having some conflicts, including with a test one I had in my config.

Also, when I did get it to activate in org, I couldn't select and insert a candidate. `TAB` moved to the next candidate, and `RET` impacted the buffer.

I'll need to dig around some more.

**Comment by mclearc** [comment]
> Also, when I did get it to activate in org, I couldn't select and insert a candidate. `TAB` moved to the next candidate, and `RET` impacted the buffer.

I think this just depends on what your keybindings are for completion-at-point. If you're using corfu you select the one to insert with `corfu-insert` (not sure what that might be bound to with evil).

**Comment by bdarcus** [comment]
I'm currently trying out a private doom corfu module, which has these bindings:

```elisp
  :bind (:map corfu-map
         ("SPC" . corfu-insert-separator)
         ("TAB" . corfu-next)
         ([tab] . corfu-next)
         ("S-TAB" . corfu-previous)
         ([backtab] . corfu-previous)))
```

**Comment by bdarcus** [comment]
But I will say that when I use corfu with other capf's, in other modes (like lisp), I don't see the same behavior.

Still, I suspect there may be some issue here.

**Comment by mclearc** [comment]
Here are the bindings I use:

```emacs-lisp
  :bind
  (:map corfu-map
   ("C-j"      . corfu-next)
   ("C-k"      . corfu-previous)
   ("C-g"      . corfu-quit)
   ("M-l"      . corfu-show-location)
   ("M-SPC" . corfu-insert-separator)
   ("<escape>" . corfu-quit)
   ("<return>" . corfu-insert)
   ("TAB" . corfu-insert)
   ([tab] . corfu-insert))
```

**Comment by mclearc** [comment]
FYI: https://github.com/mclear-tools/citar-capf

**Comment by bdarcus** [comment]
Cool!

I'll install it from there, and try to figure out my config issue, and if any bugs etc report them there.
