### ISSUE TITLE
How to get a list of keys for references that have notes?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#594]
I thought this would be straightforward, and it's possible I'm missing something, but I can't figure it out.

From a discussion on a related project.

Thoughts on this @roshanshariff @aikrahguzar?

EDIT: I linked a simple PR to make this easier.

------

So you need a list keys for all entries that have associated notes?

E.g.:

```elisp
("doe1" "doe2" "doe3")
```

That's all?

If so, could you not just take the code you reference above to filter the candidates, and from there extract the keys?

EDIT: maybe not. I'll dig a little.

_Originally posted by @bdarcus in https://github.com/Vidianos-Giannitsis/zetteldesk.el/issues/5#issuecomment-1129300695_

**Comment by roshanshariff** [comment]
This function seems to do the trick:
```elisp
(defun citar-get-keys-with-note (&optional force-rebuild-cache)
  (let* ((candidates (citar--get-candidates force-rebuild-cache))
         (hasnotep (citar-has-note)))
    (seq-map #'cadr (seq-filter (pcase-lambda (`(_ ,citekey . ,entry))
                                  (funcall hasnotep citekey entry))
                                candidates))))
```

The `seq-filter` call gets the list of candidates that have notes, each element being of the form `(candstring citekey . entry)`, and the `seq-map` extracts just the citekeys from that filtered list.

**Comment by roshanshariff** [comment]
Also, I didn't fully read the context of this request, but one thing to beware of if you're adding the "has-note" key to citation entries: the candidates are usually only refreshed when the bib file is updated on disk. If notes are created/deleted without the bib file being changed, the has-note information will get out of date.

That is avoided if you call `citar--has-note` freshly every time and use the returned predicate to filter. That'll make it scan your notes directory each time. I'm not sure if that matters in this case.

**Comment by bdarcus** [comment]
What is that `pcase-lambda` doing? Why is that needed?

> If notes are created/deleted without the bib file being changed, the has-note information will get out of date.

Yes; good point.

Hmm; need to think on that a bit.

**Comment by aikrahguzar** [comment]
> If notes are created/deleted without the bib file being changed, the has-note information will get out of date.

I think `citar-filenotify` can handle this, add `'notes` to the `citar-filenotify-files`.

**Comment by bdarcus** [comment]
> think `citar-filenotify` can handle this, add `'notes` to the `citar-filenotify-files`.

Yes, it can.

But the downside I can imagine is that's a more user-facing option, that a programmer wouldn't have any control of.

I suppose we could have both options?

**Comment by aikrahguzar** [comment]
> But the downside I can imagine is that's a more user-facing option, that a programmer wouldn't have any control of.
> 
> I suppose we could have both options?

I don't understand what are the two options you are referring to. But it should be user option although I think default can be changed to `'(bibliography notes)`. It won't hurt people like me who haven't set a notes path and if people with notes opted in to filenotify they probably want to have their notes taken into account?

**Comment by bdarcus** [comment]
> I don't understand what are the two options you are referring to. 

The linked PR (add cons cells to the candidate entries) and the suggestion from Rohan.

Or, I was thinking maybe `citar---get-candidstes` should allow a filter arg too?

> But it should be user option although I think default can be changed to '(bibliography notes). It won't hurt people like me who haven't set a notes path and if people with notes opted in to filenotify they probably want to have their notes taken into account?

Now that I think about it, I'm not actually sure, TBH.

Maybe @Vidianos-Giannitsis can weigh in.
