### ISSUE TITLE
Make PDF viewer selectable - to be emacs external

### ISSUE THREAD

**Issue by hpgisler** [bdarcus/citar#600]
**Not actually a big problem - more a nice to have**

When opening a PDF which is associated with a cite in the bib file (via file tag),
it would be nice, to be able to configure an external application (e.g. via xdg-open) for viewing it,
instead emacs' internal viewer.

**Describe the solution you'd like**

Apart from overwriting the following function like so:

```
	(defun citar-file-open (file)
		"Open FILE.
Overwritten by hgi, to open pdf files from citar
in external PDF viewer and not in internal one."
		(if (or (equal (file-name-extension file) "pdf") (equal (file-name-extension file) "html"))
				(citar-file-open-external (expand-file-name file))
			(funcall citar-file-open-function (expand-file-name file))))
```

it would be nice to be able to set this behavior somehow (e.g. via variable), etc.

Or does such an option already exist? (I didn't find anything).

**Comment by bdarcus** [comment]
> Or does such an option already exist? (I didn't find anything).

Yes; see `citar-file-open-function`.

There's also an idea in #507 to make this configurable by extension.
