### ISSUE TITLE
Using `org-citar-edit-note` as note open function fails when Org Roam note template does not have `:immediate-finish t`

### ISSUE THREAD

**Issue by balajisivaraman** [bdarcus/citar#613]
**Describe the bug**

Setting `citar-open-note-functions` to `'(orb-citar-edit-note)` causes the `citar-open-notes` action to fail with the following error when the Org Roam capture template used does not have `:immediate-finish t`:

```
(wrong-number-of-arguments #<subr citar-org-format-note-default> 2)
```

**To Reproduce**
1. Set the value of `org-roam-capture-templates` as below (with other Org Roam configuration as needed):

```elisp
(setq 
org-roam-directory "~/notes"
org-roam-capture-templates
`(("n" "ref + noter" plain
      "%?"
      :target
      (file+head
       "bibliography/${citekey}.org"
       ":PROPERTIES:
:ID: %(shell-command-to-string \"uuidgen\"):ROAM_REFS: ${ref}
:END:
#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}\n

- tags ::
- keywords :: ${keywords}

* ${title}
  :PROPERTIES:
  :Custom_ID: ${citekey}
  :URL: ${url}
  :AUTHOR: ${author}
  :NOTER_DOCUMENT: %(orb-process-file-field \"${citekey}\")
  :NOTER_PAGE:
  :END:\n\n")
  :unnarrowed t))
```

3. Set value of `citar-open-note-functions` to `'(orb-citar-edit-note)`.
4. Do `M-x` `citar-insert-reference`, choose an entry from the list, and then do `embark-act` on it.
5. From the Embark actions list, choose `n` for `Open note`.

**Expected behavior**
I should be taken to the newly created Org Roam note file for the entry where I can start typing my notes, and then do `C-c C-c` as per the normal Org Capture process to finalize the capture.

**Emacs version:** `GNU Emacs 28.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-05-22`

**Additional context**

I have performed initial debugging and figured out that this is due to the recent changes made as part of da5f0c5449675fd708df15aa635f0dbd7bb02a29.

Specifically, it is happening in the `citar--open-notes` function recaptured here:

```elisp
(defun citar--open-notes (key entry)
  "Open note(s) associated with KEY and ENTRY."
  (or (seq-some
       (lambda (opener)
         (funcall opener key entry)) citar-open-note-functions)
      (funcall citar-create-note-function key entry)))
```

`orb-citar-edit-note` follows through a chain of method calls before finally ending up in `org-capture`. The last two lines of this are reproduced here:

```elisp
(when (org-capture-get :immediate-finish)
	  (org-capture-finalize))
```

As we can see, this method only returns `t` if it goes through the above block of code and `org-capture-finalize` is run. Otherwise it returns `nil` immediately and waits for the user to finalize the capture by pressing `C-c C-c`. Since the `citar--open-notes` function above sees `nil`, it goes through to the default `citar-create-note-function`, which is still taking 3 arguments (`key`, `entry` and `filepath`) instead of the two that `citar-file--open-note` takes.

**Potential fixes**
1. I think `citar--open-notes` needs to fall back to `citar-file--open-note` instead of `citar-create-note-function` for consistency.
2. As for the `orb-citar-edit-note` issue, if we do not want to pollute `citar` with `org-capture` stuff, I think it makes sense for us to add a word in the `README` highlighting that the bibliography notes template needs to have `:immediate-finish t` on it.

Thank you for the great package, and I would be happy to put in the simple fix above and send a PR if needed.

**Comment by bdarcus** [comment]
> I would be happy to put in the simple fix above and send a PR if needed.

Yes please!

**Comment by balajisivaraman** [comment]
@bdarcus, Thank you for the quick response. Just to confirm, do you also want me to update the relevant section in the README?

**Comment by bdarcus** [comment]
> @bdarcus, Thank you for the quick response. Just to confirm, do you also want me to update the relevant section in the README?

Sorry; was obviously in a hurry.

Yes.

BTW, you may be interested in #609. The commit you mentioned is in part to enable that, but that's still WIP.

**Comment by balajisivaraman** [comment]
@bdarcus, Thank you. I had a brief look at it. I will check it out in detail and am most definitely looking forward to it.
